// monthly_challenges.js - 36-month scripted events for Gaza war simulation
// Oct 2023 (month 1) through Jan 2026 (month 36)

const MONTHLY_CHALLENGES = [

  // ===== MONTH 1: First Displacement =====
  {
    id: 'displacement_1',
    month: 1,
    recurring: true,
    autoEvent: false,
    titleAr: 'النزوح الأول',
    titleEn: 'First Displacement',
    storyAr: 'أكتوبر 2023. أوامر الإخلاء تصدر. الحي يفرغ حولك.\n1.1 مليون شخص يواجهون نفس القرار.\nماذا تفعل؟',
    storyEn: 'October 2023. Evacuation orders issued. The neighborhood empties around you.\n1.1 million people face the same decision.\nWhat do you do?',
    choices: [
      {
        textAr: 'مشي على الأقدام (مجاناً)',
        textEn: 'Walk on foot (free)',
        oneTimeCost: 0,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -20,
        deathRisk: 0.05,
        injuryRisk: 0,
        burdenId: 'shelter_walk',
        burdenLabelAr: 'إيجار خيمة وأفرشة',
        burdenLabelEn: 'Tent & bedding rental',
        shelterSetupCost: 3000,
        consequence: null,
        messageAr: 'مشيتم ساعات. الطريق مكتظ. بعض الأسر لم تصل.',
        messageEn: 'You walked for hours. The road was crowded. Some families never arrived.',
      },
      {
        textAr: 'شاحنة نقل ($1,500)',
        textEn: 'Hire a truck ($1,500)',
        oneTimeCost: 1500,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'shelter_truck',
        burdenLabelAr: 'إيجار خيمة',
        burdenLabelEn: 'Tent rental',
        shelterSetupCost: 1000,
        consequence: null,
        messageAr: 'ركبتم شاحنة. وصلتم. الخيمة تنتظر.',
        messageEn: 'You rode a truck. You arrived. The tent awaits.',
      },
      {
        textAr: 'البقاء في البيت (خطر شديد)',
        textEn: 'Stay home (very dangerous)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0.15,
        injuryRisk: 0.20,
        captureRisk: 0.10,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'stay_dangerous',
        messageAr: 'بقيتم. القصف يشتد. الجيران غادروا. أنتم وحدكم.',
        messageEn: 'You stayed. The bombing intensified. The neighbors left. You are alone.',
      },
    ],
    autoEffect: null,
    realFactAr: 'أكتوبر 2023: أُمر 1.1 مليون شخص بالإخلاء خلال 24 ساعة',
    realFactEn: 'October 2023: 1.1 million people ordered to evacuate within 24 hours',
  },

  // ===== MONTH 2: Water Crisis =====
  {
    id: 'water_crisis',
    month: 2,
    recurring: true,
    autoEvent: false,
    titleAr: 'انقطاع المياه',
    titleEn: 'Water Crisis',
    storyAr: 'نوفمبر 2023. شبكة المياه توقفت.\n94% انخفاض في إمدادات المياه.\nالأطفال يحصلون على 1.5 لتر في اليوم.',
    storyEn: 'November 2023. The water network has stopped.\n94% drop in water supply.\nChildren receive 1.5 liters per day.',
    choices: [
      {
        textAr: 'شراء مياه ($300/شهر)',
        textEn: 'Buy water ($300/month)',
        oneTimeCost: 0,
        monthlyCost: 300,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'water_purchase',
        burdenLabelAr: 'شراء مياه',
        burdenLabelEn: 'Water purchase',
        consequence: null,
        messageAr: 'تشترون المياه بسعر الحرب. مكلف لكنه ضروري.',
        messageEn: 'You buy water at war prices. Expensive but necessary.',
      },
      {
        textAr: 'تعبئة يدوية من مصادر بعيدة (3 ساعات/يوم)',
        textEn: 'Manual collection from distant sources (3 hours/day)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 3,
        healthEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'تمشون كيلومترات لجلب المياه. متعب جداً.',
        messageEn: 'You walk kilometers to collect water. Exhausting.',
      },
      {
        textAr: 'الاستغناء عن المياه النظيفة (خطر صحي)',
        textEn: 'Go without clean water (health risk)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -20,
        diseaseRisk: 0.15,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'بلا مياه نظيفة. الأمراض تبدأ تظهر.',
        messageEn: 'Without clean water. Diseases begin to appear.',
      },
    ],
    autoEffect: null,
    realFactAr: 'نوفمبر 2023: 94% انخفاض في إمدادات المياه — الأطفال يحصلون على 1.5 لتر/يوم',
    realFactEn: 'November 2023: 94% drop in water supply — children received 1.5L/day',
  },

  // ===== MONTH 2: Power/Internet Outage =====
  {
    id: 'power_outage',
    month: 2,
    recurring: true,
    autoEvent: false,
    titleAr: 'انقطاع الكهرباء والإنترنت',
    titleEn: 'Power & Internet Cut',
    storyAr: 'الكهرباء انقطعت منذ الأسابيع الأولى.\nالإنترنت متقطع. لا تواصل مع العالم.\nكيف تتعامل مع الظلام؟',
    storyEn: 'Electricity has been cut since the first weeks.\nInternet is sporadic. No contact with the world.\nHow do you deal with the darkness?',
    choices: [
      {
        textAr: 'شراء مولّد كهرباء ($3,000 مرة واحدة)',
        textEn: 'Buy a generator ($3,000 one-time)',
        oneTimeCost: 3000,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'اشتريتم مولداً. الكهرباء عادت جزئياً. ترف نسبي.',
        messageEn: 'You bought a generator. Electricity returned partially.',
      },
      {
        textAr: 'شراء ساعات محدودة من التجار ($100/شهر)',
        textEn: 'Buy limited hours from vendors ($100/month)',
        oneTimeCost: 0,
        monthlyCost: 100,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'power_vendor',
        burdenLabelAr: 'كهرباء التجار',
        burdenLabelEn: 'Vendor electricity',
        consequence: null,
        messageAr: 'ساعات قليلة من الكهرباء تكفي للأساسيات.',
        messageEn: 'A few hours of electricity for basics.',
      },
      {
        textAr: 'الاستغناء التام عن الكهرباء',
        textEn: 'Go completely without power',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 1,
        healthEffect: 0,
        moraleEffect: -10,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'الظلام يطول. المعنويات تهبط. لكن المال يُوفّر.',
        messageEn: 'The darkness grows. Morale drops. But money is saved.',
      },
    ],
    autoEffect: null,
    realFactAr: 'انقطعت الكهرباء عن غزة بالكامل منذ أكتوبر 2023',
    realFactEn: 'Gaza lost all electricity from October 2023',
  },

  // ===== MONTH 3: Potable Water Shortage =====
  {
    id: 'potable_water',
    month: 3,
    recurring: true,
    autoEvent: false,
    titleAr: 'نقص مياه الشرب النقية',
    titleEn: 'Potable Water Shortage',
    storyAr: 'ديسمبر 2023. حتى المياه المشتراة أصبحت ملوثة.\nتحتاج إلى مياه نقية للشرب والطهي.',
    storyEn: 'December 2023. Even purchased water is becoming contaminated.\nYou need clean water for drinking and cooking.',
    choices: [
      {
        textAr: 'شراء مياه نقية معبأة ($100/شهر)',
        textEn: 'Buy bottled clean water ($100/month)',
        oneTimeCost: 0,
        monthlyCost: 100,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'potable_water',
        burdenLabelAr: 'مياه الشرب النقية',
        burdenLabelEn: 'Bottled drinking water',
        consequence: null,
        messageAr: 'مياه نظيفة. أغلى لكن أأمن.',
        messageEn: 'Clean water. More expensive but safer.',
      },
      {
        textAr: 'جمع المياه يدوياً من نقاط التوزيع',
        textEn: 'Collect manually from distribution points',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 3,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'تنتظرون ساعات في الطابور. مضنٍ لكن مجاني.',
        messageEn: 'You wait hours in line. Exhausting but free.',
      },
      {
        textAr: 'استخدام المياه المتاحة (خطر أمراض)',
        textEn: 'Use available water (disease risk)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -15,
        diseaseRisk: 0.20,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'مياه غير آمنة. المعدة تُعاني.',
        messageEn: 'Unsafe water. Stomach problems begin.',
      },
    ],
    autoEffect: null,
    realFactAr: 'ديسمبر 2023: تلوث 70% من مصادر المياه الجوفية',
    realFactEn: 'December 2023: 70% of groundwater sources contaminated',
  },

  // ===== MONTH 4: Banking Crisis (Auto) =====
  {
    id: 'banking_crisis_1',
    month: 4,
    recurring: false,
    autoEvent: true,
    titleAr: 'أزمة السيولة المصرفية',
    titleEn: 'Banking Crisis',
    storyAr: 'يناير 2024. البنوك أغلقت. تدفع 10% لسحب راتبك.\nهذه التكلفة مؤلمة لكنك لا تملك خياراً.',
    storyEn: 'January 2024. Banks closed. You pay 10% to withdraw your salary.\nThis cost is painful but you have no choice.',
    choices: [],
    autoEffect: { salaryPenaltyAdd: 0.10 },
    realFactAr: 'أغلقت بنوك غزة — العمال يدفعون 10-30% عمولة لصرافين غير رسميين',
    realFactEn: 'Gaza banks closed completely — workers paid 10-30% fees to unlicensed money changers',
  },

  // ===== MONTH 5: Coffee/Beverages Shortage =====
  {
    id: 'beverages_shortage',
    month: 5,
    recurring: false,
    autoEvent: false,
    titleAr: 'نقص القهوة والمشروبات',
    titleEn: 'Coffee & Beverages Shortage',
    storyAr: 'فبراير 2024. البضائع الأساسية نفدت من الأسواق.\nالقهوة والشاي أصبحا رفاهية.\nصغيرة لكنها تعني الكثير.',
    storyEn: 'February 2024. Basic goods have run out of markets.\nCoffee and tea have become luxuries.\nSmall but it means a lot.',
    choices: [
      {
        textAr: 'شراء من السوق السوداء ($100/شهر)',
        textEn: 'Buy from black market ($100/month)',
        oneTimeCost: 0,
        monthlyCost: 100,
        workHoursLost: 0,
        healthEffect: 0,
        moraleEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'beverages',
        burdenLabelAr: 'مشروبات',
        burdenLabelEn: 'Beverages',
        consequence: null,
        messageAr: 'فنجان قهوة في الحرب. يكفي للاستمرار.',
        messageEn: 'A cup of coffee in war. Enough to keep going.',
      },
      {
        textAr: 'الامتناع التام',
        textEn: 'Go without entirely',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        moraleEffect: -8,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'تصبرون. الأموال محدودة. المعنويات تتراجع قليلاً.',
        messageEn: 'You endure. Money is limited. Morale drops slightly.',
      },
    ],
    autoEffect: null,
    realFactAr: 'أسعار السلع الأساسية ارتفعت 400% في غزة بداية 2024',
    realFactEn: 'Basic goods prices rose 400% in Gaza by early 2024',
  },

  // ===== MONTH 6: Cooking Gas Shortage =====
  {
    id: 'cooking_gas',
    month: 6,
    recurring: true,
    autoEvent: false,
    titleAr: 'نقص غاز الطهي',
    titleEn: 'Cooking Gas Shortage',
    storyAr: 'مارس 2024. الغاز المنزلي انتهى.\nالطبخ أصبح مشكلة يومية.\nكيف تُطعم عائلتك؟',
    storyEn: 'March 2024. Domestic gas has run out.\nCooking has become a daily problem.\nHow do you feed your family?',
    choices: [
      {
        textAr: 'شراء غاز بسعر الحرب ($300/شهر)',
        textEn: 'Buy gas at war price ($300/month)',
        oneTimeCost: 0,
        monthlyCost: 300,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'cooking_gas',
        burdenLabelAr: 'غاز الطهي',
        burdenLabelEn: 'Cooking gas',
        consequence: null,
        messageAr: 'غاز بسعر خيالي. لكن الطعام يُطهى.',
        messageEn: 'Gas at an outrageous price. But food gets cooked.',
      },
      {
        textAr: 'الطهي على الأخشاب ($100/شهر)',
        textEn: 'Cook on wood fire ($100/month)',
        oneTimeCost: 0,
        monthlyCost: 100,
        workHoursLost: 0,
        healthEffect: -3,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'wood_cooking',
        burdenLabelAr: 'أخشاب للطهي',
        burdenLabelEn: 'Firewood cooking',
        consequence: null,
        messageAr: 'نار الأخشاب. أقل تكلفة. الدخان يزعج الأطفال.',
        messageEn: 'Wood fire. Less cost. Smoke bothers the children.',
      },
      {
        textAr: 'أكل بارد وطعام خام',
        textEn: 'Eat cold and raw food',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -10,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'طعام بارد وخام. الصحة تتراجع.',
        messageEn: 'Cold and raw food. Health deteriorates.',
      },
    ],
    autoEffect: null,
    realFactAr: 'غزة 2024: غاز الطهي اختفى تماماً — السكان يحرقون الخشب والبلاستيك',
    realFactEn: 'Gaza 2024: Cooking gas disappeared — residents burning wood and plastic',
  },

  // ===== MONTH 6: Vegetables/Fruits Shortage =====
  {
    id: 'vegetables_shortage',
    month: 6,
    recurring: true,
    autoEvent: false,
    titleAr: 'اختفاء الخضار والفواكه',
    titleEn: 'Vegetables & Fruits Disappear',
    storyAr: 'الأسواق فارغة من الخضار والفواكه.\nسوء التغذية يبدأ يظهر على الأطفال.',
    storyEn: 'Markets are empty of vegetables and fruits.\nMalnutrition starts to show in children.',
    choices: [
      {
        textAr: 'شراء من التجار ($200/شهر)',
        textEn: 'Buy from traders ($200/month)',
        oneTimeCost: 0,
        monthlyCost: 200,
        workHoursLost: 0,
        healthEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'vegetables',
        burdenLabelAr: 'خضار وفواكه',
        burdenLabelEn: 'Vegetables & fruits',
        consequence: null,
        messageAr: 'خضار بأسعار مبالغ فيها. لكن الأطفال يأكلون.',
        messageEn: 'Vegetables at inflated prices. But the children eat.',
      },
      {
        textAr: 'الاستغناء (نقص غذائي)',
        textEn: 'Go without (nutritional deficiency)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -8,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'بلا خضار. سوء التغذية يتراكم.',
        messageEn: 'Without vegetables. Malnutrition accumulates.',
      },
    ],
    autoEffect: null,
    realFactAr: 'ربيع 2024: 100% من سكان غزة يعانون من انعدام الأمن الغذائي',
    realFactEn: 'Spring 2024: 100% of Gaza population experiencing food insecurity',
  },

  // ===== MONTH 6: Emigration Option =====
  {
    id: 'emigration_window',
    month: 6,
    recurring: false,
    autoEvent: false,
    titleAr: 'فرصة السفر والهجرة',
    titleEn: 'Emigration Window',
    storyAr: 'مارس 2024. فُتح باب السفر لمن يملك المال.\nتذاكر وإجراءات ورشاوى. المجموع: $30,000.\nإما الرحيل أو البقاء في الإبادة.',
    storyEn: 'March 2024. The door of travel opened for those with money.\nTickets, procedures, bribes. Total: $30,000.\nLeave or stay in the genocide.',
    choices: [
      {
        textAr: 'السفر مع الأسرة كاملة ($30,000)',
        textEn: 'Leave with the whole family ($30,000)',
        oneTimeCost: 30000,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'emigrate',
        messageAr: 'غادرتم. نجوتم بأرواحكم. البيت... لن يعود.',
        messageEn: 'You left. You survived with your lives. The home... will never return.',
      },
      {
        textAr: 'البقاء — هذه أرضنا',
        textEn: 'Stay — this is our land',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'stay_dangerous',
        messageAr: 'قررتم البقاء. هذا اختياركم. هذه أرضكم.',
        messageEn: 'You decided to stay. This is your choice. This is your land.',
      },
    ],
    autoEffect: null,
    realFactAr: 'كلف السفر لمصر عبر رفح ما بين $5,000 و$30,000 للأسرة الواحدة',
    realFactEn: 'Travel to Egypt through Rafah cost between $5,000 and $30,000 per family',
  },

  // ===== MONTH 7: Second Displacement =====
  {
    id: 'displacement_2',
    month: 7,
    recurring: true,
    autoEvent: false,
    titleAr: 'النزوح الثاني',
    titleEn: 'Second Displacement',
    storyAr: 'يناير 2024. أوامر إخلاء جديدة.\nهذه المرة من مكان النزوح الأول.\nخسرتم كل شيء مرة. والآن مرة أخرى.',
    storyEn: 'January 2024. New evacuation orders.\nThis time from the first displacement site.\nYou lost everything once. And now again.',
    choices: [
      {
        textAr: 'مشي على الأقدام (مجاناً)',
        textEn: 'Walk on foot (free)',
        oneTimeCost: 0,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -20,
        deathRisk: 0.05,
        injuryRisk: 0,
        burdenId: 'shelter_walk_2',
        burdenLabelAr: 'إيجار خيمة ثانية',
        burdenLabelEn: 'Second tent rental',
        shelterSetupCost: 2000,
        consequence: null,
        messageAr: 'نزوح ثانٍ. الجسم أنهكه المشي. لكنكم وصلتم.',
        messageEn: 'Second displacement. The body is exhausted from walking. But you arrived.',
      },
      {
        textAr: 'شاحنة نقل ($1,500)',
        textEn: 'Hire a truck ($1,500)',
        oneTimeCost: 1500,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'shelter_truck_2',
        burdenLabelAr: 'إيجار خيمة ثانية',
        burdenLabelEn: 'Second tent rental',
        shelterSetupCost: 1000,
        consequence: null,
        messageAr: 'مرة ثانية في الشاحنة. أين تنتهي هذه الرحلة؟',
        messageEn: 'A second time in the truck. Where does this journey end?',
      },
      {
        textAr: 'البقاء مجدداً (خطر شديد جداً)',
        textEn: 'Stay again (extremely dangerous)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0.20,
        injuryRisk: 0.25,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'stay_dangerous',
        messageAr: 'بقيتم مجدداً. الخطر أضعاف ما كان. القصف في كل مكان.',
        messageEn: 'You stayed again. The danger is multiple times worse. Bombing everywhere.',
      },
    ],
    autoEffect: null,
    realFactAr: 'يناير 2024: النازحون في غزة يُنزحون مرة أخرى وثالثة ورابعة',
    realFactEn: 'January 2024: Displaced Gazans were displaced again and again',
  },

  // ===== MONTH 8: Aid Convoy =====
  {
    id: 'aid_convoy',
    month: 8,
    recurring: false,
    autoEvent: false,
    titleAr: 'قوافل المساعدات الأمريكية',
    titleEn: 'US Aid Convoy Run',
    storyAr: 'فبراير 2024. قوافل مساعدات أمريكية تصل.\nإذا ذهبت تستطيع الحصول على مؤن — لكن المخاطر حقيقية.\n112 شهيداً سقطوا في مجزرة الدقيق بنفس الطريقة.',
    storyEn: 'February 2024. US aid convoys arrive.\nIf you go you can get supplies — but the risks are real.\n112 killed in the Flour Massacre the same way.',
    choices: [
      {
        textAr: 'اذهب للمساعدات (+$1,000)',
        textEn: 'Go for the aid (+$1,000)',
        oneTimeCost: -1000,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0.10,
        injuryRisk: 0.20,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'ذهبت. الخطر حقيقي. بعض من ذهبوا لم يعودوا.',
        messageEn: 'You went. The danger is real. Some who went never returned.',
      },
      {
        textAr: 'امتنع — الأمان أهم',
        textEn: 'Refuse — safety first',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'قررت البقاء. أسرتك آمنة. لكن الطعام شحيح.',
        messageEn: 'You decided to stay. Your family is safe. But food is scarce.',
      },
    ],
    autoEffect: null,
    realFactAr: '29 فبراير 2024: مجزرة الدقيق — 112 شهيداً، 750 جريحاً عند نقطة توزيع المساعدات',
    realFactEn: 'Feb 29, 2024: Flour Massacre — 112 killed, 750 wounded at aid distribution point',
    showOnlyIfBroke: true,
  },

  // ===== MONTH 9: Baby Formula =====
  {
    id: 'baby_formula',
    month: 9,
    recurring: true,
    autoEvent: false,
    titleAr: 'حليب الأطفال الرضّع',
    titleEn: 'Baby Formula',
    storyAr: 'أبريل 2024. الأطفال الرضّع بحاجة لحليب صناعي.\nقبل الحرب: $15. الآن: $200.\nطفلك يبكي جوعاً.',
    storyEn: 'April 2024. Infants need baby formula.\nBefore the war: $15. Now: $200.\nYour baby cries from hunger.',
    choices: [
      {
        textAr: 'شراء حليب الأطفال ($200/شهر)',
        textEn: 'Buy baby formula ($200/month)',
        oneTimeCost: 0,
        monthlyCost: 200,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'baby_formula',
        burdenLabelAr: 'حليب الأطفال',
        burdenLabelEn: 'Baby formula',
        consequence: null,
        messageAr: '$200 لزجاجة حليب. أغلى شيء في الحرب: أن يأكل طفلك.',
        messageEn: '$200 for a bottle of milk. The most expensive thing in war: your child eating.',
      },
      {
        textAr: 'لا يمكن الشراء (صحة الأطفال تتراجع)',
        textEn: 'Cannot afford (children health declines)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -15,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        childrenOnly: true,
        consequence: null,
        messageAr: 'الطفل يبكي. لا يوجد حليب. الوزن ينخفض.',
        messageEn: 'The baby cries. No milk. Weight is dropping.',
      },
    ],
    autoEffect: null,
    realFactAr: 'أبريل 2024: أسعار حليب الأطفال ارتفعت 1200% — وفيات رضّع من الجوع',
    realFactEn: 'April 2024: Baby formula prices rose 1200% — infant deaths from starvation',
    showOnlyIfChildren: true,
  },

  // ===== MONTH 9: Neighbor's Plea =====
  {
    id: 'neighbor_formula',
    month: 9,
    recurring: false,
    autoEvent: false,
    titleAr: 'الجار يطرق الباب',
    titleEn: "Neighbor's Plea",
    storyAr: 'طرق الباب رجل يحمل طفله الرضيع.\n"ابني لم يأكل منذ يومين. عندك حليب؟"\nنظراته يائسة.',
    storyEn: 'A man knocked at the door carrying his infant.\n"My son hasn\'t eaten in two days. Do you have formula?"\nHis eyes are desperate.',
    choices: [
      {
        textAr: 'أعطيه من مخزونك ($200)',
        textEn: 'Give him from your stock ($200)',
        oneTimeCost: 200,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        moraleEffect: 15,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'أعطيته. قال "الله يحفظ أولادك". هذا يساوي كل شيء.',
        messageEn: 'You gave it. He said "God protect your children." That is worth everything.',
      },
      {
        textAr: 'تعتذر — لا يكفيك أنت',
        textEn: 'Apologize — not enough for yourself',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        moraleEffect: -20,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'غلقت الباب. صرخة الطفل تطاردك في نومك.',
        messageEn: 'You closed the door. The baby\'s cry haunts your sleep.',
      },
    ],
    autoEffect: null,
    realFactAr: 'في غزة 2024: الجيران يتشاركون آخر ما يملكون',
    realFactEn: 'In Gaza 2024: Neighbors share the last of what they have',
  },

  // ===== MONTH 10: Work Too Dangerous =====
  {
    id: 'work_dangerous',
    month: 10,
    recurring: false,
    autoEvent: false,
    titleAr: 'العمل أصبح خطراً على الحياة',
    titleEn: 'Work Becomes Life-Threatening',
    storyAr: 'مايو 2024. الوصول لمكان العمل أصبح مجازفة بالحياة.\nكل مهنة — طبيب، مهندس، تاجر — أصبحت هدفاً.\nالطريق إلى العمل يمر بمناطق القصف.',
    storyEn: 'May 2024. Getting to work has become a life gamble.\nEvery profession — doctor, engineer, merchant — has become a target.\nThe road to work passes through bombing zones.',
    choices: [
      {
        textAr: 'ترك العمل نهائياً (الراتب يصبح صفر)',
        textEn: 'Quit permanently (salary becomes zero)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 8,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'work_stop',
        messageAr: 'تركت العمل. آمن. لكن الراتب انتهى. المدخرات تنفد الآن.',
        messageEn: 'You quit work. Safe. But the salary ended. Savings are now depleting.',
      },
      {
        textAr: 'الاستمرار بالعمل (خطر الموت 5%/شهر)',
        textEn: 'Continue working (5% death risk/month)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        monthlyDeathHazard: 0.05,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'تستمر. تعرف الخطر. لكن الأسرة تحتاج الراتب.',
        messageEn: 'You continue. You know the risk. But the family needs the salary.',
      },
    ],
    autoEffect: null,
    realFactAr: 'غزة 2024: اغتيال أطباء ومهندسين وصحفيين في مناطق العمل',
    realFactEn: 'Gaza 2024: Doctors, engineers, and journalists targeted at work',
  },

  // ===== MONTH 11: Banking Crisis Escalation (Auto) =====
  {
    id: 'banking_crisis_2',
    month: 11,
    recurring: false,
    autoEvent: true,
    titleAr: 'تصاعد أزمة البنوك',
    titleEn: 'Banking Crisis Escalation',
    storyAr: 'يونيو 2024. ارتفعت رسوم سحب الراتب إلى 20%.\nبعض البنوك أغلقت نهائياً.\nالسيولة شبه منعدمة.',
    storyEn: 'June 2024. Salary withdrawal fees rose to 20%.\nSome banks closed permanently.\nLiquidity is nearly non-existent.',
    choices: [],
    autoEffect: { salaryPenaltyAdd: 0.20 },
    realFactAr: 'يونيو 2024: انهار النظام المصرفي في غزة بالكامل — رسوم تصل 30%',
    realFactEn: 'June 2024: Gaza banking system fully collapsed — fees reaching 30%',
  },

  // ===== MONTH 12: Third Displacement =====
  {
    id: 'displacement_3',
    month: 12,
    recurring: true,
    autoEvent: false,
    titleAr: 'النزوح الثالث — رفح',
    titleEn: 'Third Displacement — Rafah',
    storyAr: 'مايو 2024. أوامر إخلاء من رفح.\n1.4 مليون شخص في المواصي — المنطقة "الآمنة".\nالمواصي نفسها قُصفت لاحقاً.',
    storyEn: 'May 2024. Evacuation orders from Rafah.\n1.4 million in Al-Mawasi — the "safe" area.\nAl-Mawasi itself was later bombed.',
    choices: [
      {
        textAr: 'مشي إلى المواصي (مجاناً)',
        textEn: 'Walk to Al-Mawasi (free)',
        oneTimeCost: 0,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -20,
        deathRisk: 0.06,
        injuryRisk: 0,
        burdenId: 'shelter_mawasi',
        burdenLabelAr: 'خيمة المواصي',
        burdenLabelEn: 'Al-Mawasi tent',
        shelterSetupCost: 2000,
        consequence: null,
        messageAr: 'المواصي. رمال وبحر وخيام. ليست آمنة كما قالوا.',
        messageEn: 'Al-Mawasi. Sand and sea and tents. Not safe as they said.',
      },
      {
        textAr: 'شاحنة نقل ($1,500)',
        textEn: 'Hire a truck ($1,500)',
        oneTimeCost: 1500,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'shelter_truck_3',
        burdenLabelAr: 'خيمة المواصي',
        burdenLabelEn: 'Al-Mawasi tent',
        shelterSetupCost: 1000,
        consequence: null,
        messageAr: 'الشاحنة الثالثة. تعلمتم أن تحملوا فقط الضروري.',
        messageEn: 'The third truck. You learned to carry only the essentials.',
      },
      {
        textAr: 'البقاء في رفح (خطر اجتياح عسكري)',
        textEn: 'Stay in Rafah (military invasion risk)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0.25,
        injuryRisk: 0.30,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'stay_dangerous',
        messageAr: 'بقيتم في رفح. الاجتياح يقترب. الأزقة تقتل.',
        messageEn: 'You stayed in Rafah. The invasion approaches. The alleys kill.',
      },
    ],
    autoEffect: null,
    realFactAr: 'مايو 2024: اجتاح الجيش الإسرائيلي رفح رغم وجود 1.4 مليون نازح',
    realFactEn: 'May 2024: Israeli army invaded Rafah despite 1.4 million displaced there',
  },

  // ===== MONTH 13: Baby Formula Price Rise (Auto) =====
  {
    id: 'formula_price_rise',
    month: 13,
    recurring: false,
    autoEvent: true,
    titleAr: 'ارتفاع سعر حليب الأطفال',
    titleEn: 'Baby Formula Price Rise',
    storyAr: 'يونيو 2024. الحليب الصناعي ارتفع إلى $300/شهر.\n(كان $200 الشهر الماضي)\nالتضخم لا يتوقف.',
    storyEn: 'June 2024. Baby formula rose to $300/month.\n(Was $200 last month)\nInflation does not stop.',
    choices: [],
    autoEffect: { updateBurdenId: 'baby_formula', newAmount: 300 },
    realFactAr: 'غزة 2024: أسعار حليب الأطفال ضاعفت كل شهر',
    realFactEn: 'Gaza 2024: Baby formula prices doubled each month',
    showOnlyIfChildren: true,
  },

  // ===== MONTH 14: Flour Scarcity =====
  {
    id: 'flour_scarcity',
    month: 14,
    recurring: true,
    autoEvent: false,
    titleAr: 'شح الدقيق — طعام الحيوانات',
    titleEn: 'Flour Scarcity — Animal Feed',
    storyAr: 'يوليو 2024. اختفى الدقيق الأبيض تماماً.\nمن يبيع، يبيع دقيق أعلاف حيوانات.\nمغشوش. يضر الصحة على المدى البعيد.\nلكن الجوع لا ينتظر.',
    storyEn: 'July 2024. White flour completely disappeared.\nWhat is sold is animal feed flour.\nAdulterated. Slowly harms health.\nBut hunger doesn\'t wait.',
    choices: [
      {
        textAr: 'شراء دقيق الأعلاف ($400/شهر)',
        textEn: 'Buy animal feed flour ($400/month)',
        oneTimeCost: 0, monthlyCost: 400, workHoursLost: 0,
        healthEffect: -5,
        deathRisk: 0, injuryRisk: 0,
        burdenId: 'animal_flour', burdenLabelAr: 'دقيق الأعلاف', burdenLabelEn: 'Animal flour',
        consequence: null,
        messageAr: 'اشتريتم. الطعام مر. الصحة تتراجع ببطء. لكن البطون ليست فارغة.',
        messageEn: 'Bought. Food tastes bitter. Health slowly declines. But bellies aren\'t empty.',
      },
      {
        textAr: 'الامتناع — جوع كامل',
        textEn: 'Refuse — complete hunger',
        oneTimeCost: 0, monthlyCost: 0, workHoursLost: 0,
        healthEffect: -20,
        deathRisk: 0.05, injuryRisk: 0,
        childrenOnly: false,
        burdenId: null, burdenLabelAr: '', burdenLabelEn: '',
        consequence: null,
        messageAr: 'لا طعام. الأجساد تضعف. الأطفال يبكون من الجوع.',
        messageEn: 'No food. Bodies weaken. Children cry from hunger.',
      },
    ],
    autoEffect: null,
    realFactAr: 'غزة 2024: دقيق أعلاف الحيوانات هو الوحيد المتاح في الأسواق — يحتوي على معادن ضارة بالبشر',
    realFactEn: 'Gaza 2024: Animal feed flour was the only available option — contains minerals harmful to humans',
  },

  // ===== MONTH 15: Polio Returns =====
  {
    id: 'polio_returns',
    month: 15,
    recurring: false,
    autoEvent: false,
    titleAr: 'عودة شلل الأطفال',
    titleEn: 'Polio Returns',
    storyAr: 'أغسطس 2024.\nشلل الأطفال عاد لغزة بعد 25 عاماً من غيابه.\nطفل عمره 10 أشهر أُصيب بشلل دائم.\nالتطعيم: 4 أيام فقط — في هدنة مشروطة.',
    storyEn: 'August 2024.\nPolio returned to Gaza after 25 years.\nA 10-month-old was permanently paralyzed.\nVaccination window: only 4 days — in a conditional pause.',
    choices: [
      {
        textAr: 'حملة تطعيم طارئة ($300)',
        textEn: 'Emergency vaccination ($300)',
        oneTimeCost: 300, monthlyCost: 0, workHoursLost: 0,
        healthEffect: 0, deathRisk: 0, injuryRisk: 0,
        burdenId: null, burdenLabelAr: '', burdenLabelEn: '',
        consequence: null,
        messageAr: 'لقّحتم الأطفال. الأمل أن اللقاح يصل بالوقت.',
        messageEn: 'Children vaccinated. Hope the vaccine arrives in time.',
      },
      {
        textAr: 'لا يمكن الوصول إلى اللقاح',
        textEn: 'Cannot access vaccine',
        oneTimeCost: 0, monthlyCost: 0, workHoursLost: 0,
        healthEffect: -15, deathRisk: 0, injuryRisk: 0,
        childrenOnly: true,
        burdenId: null, burdenLabelAr: '', burdenLabelEn: '',
        consequence: null,
        messageAr: 'لا لقاح. الخطر قائم. تصلّي ألا يصاب أطفالك.',
        messageEn: 'No vaccine. Risk remains. You pray your children are spared.',
      },
    ],
    autoEffect: null,
    showOnlyIfChildren: true,
    realFactAr: 'أغسطس 2024: 559,161 طفل لُقّحوا خلال هدنة 4 أيام فقط',
    realFactEn: 'August 2024: 559,161 children vaccinated in a 4-day humanitarian pause',
  },

  // ===== MONTH 15 also: Winter Crisis =====
  {
    id: 'winter_crisis',
    month: 15,
    recurring: false,
    autoEvent: false,
    titleAr: 'أزمة الشتاء — غرق الخيام',
    titleEn: 'Winter Crisis — Flooded Tents',
    storyAr: 'نوفمبر 2024. الأمطار قادمة.\nالخيام تغرق. الأطفال يبللون وهم نائمون.\nحماية الخيمة ضرورة أو الأمراض تجتاح الأسرة.',
    storyEn: 'November 2024. Rains are coming.\nTents flood. Children soaked while sleeping.\nWaterproofing is essential or illness sweeps the family.',
    choices: [
      {
        textAr: 'شراء شوادر وعزل ($500 لـ3 أشهر)',
        textEn: 'Buy waterproofing ($500 for 3 months)',
        oneTimeCost: 500, monthlyCost: 0, workHoursLost: 0,
        healthEffect: 0, deathRisk: 0, injuryRisk: 0,
        burdenId: null, burdenLabelAr: '', burdenLabelEn: '',
        consequence: null,
        messageAr: 'الخيمة محمية. باردة لكن جافة.',
        messageEn: 'Tent is protected. Cold but dry.',
      },
      {
        textAr: 'الامتناع — لا مال',
        textEn: 'Skip — no money',
        oneTimeCost: 0, monthlyCost: 0, workHoursLost: 0,
        healthEffect: -20, deathRisk: 0, injuryRisk: 0,
        burdenId: null, burdenLabelAr: '', burdenLabelEn: '',
        consequence: null,
        messageAr: 'الخيمة تغرق. الأطفال يرتجفون. الأمراض تبدأ.',
        messageEn: 'Tent floods. Children shiver. Illness begins.',
      },
    ],
    autoEffect: null,
    realFactAr: 'شتاء 2024: أكثر من مليون نازح في خيام بلا تدفئة في غزة',
    realFactEn: 'Winter 2024: Over 1 million displaced in tents without heating in Gaza',
  },

  // ===== MONTH 16: Debt Ceiling Black Market =====
  {
    id: 'debt_black_market',
    month: 16,
    recurring: false,
    autoEvent: false,
    titleAr: 'استغلال حد الاستدانة — السوق السوداء',
    titleEn: 'Debt Ceiling — Black Market Exploitation',
    storyAr: 'التجار يعرفون أنك مفلس.\nيعرضون رهن ممتلكاتك مقابل كاش.\nأو بيع مساعداتك الإنسانية بأثمان بخسة.\nلا يوجد خيار جيد.',
    storyEn: 'Traders know you\'re broke.\nThey offer to pawn your belongings for cash.\nOr sell your humanitarian aid at rock-bottom prices.\nThere is no good option.',
    choices: [
      {
        textAr: 'رهن ممتلكات ($500 كاش، خسارة دائمة)',
        textEn: 'Pawn belongings ($500 cash, permanent loss)',
        oneTimeCost: -500, monthlyCost: 0, workHoursLost: 0,
        healthEffect: 0, deathRisk: 0, injuryRisk: 0,
        moraleEffect: -20,
        burdenId: null, burdenLabelAr: '', burdenLabelEn: '',
        consequence: null,
        messageAr: 'بعت ما تبقى من حياتك السابقة. 500 دولار. تكفي أسبوعين.',
        messageEn: 'Sold what remains of your past life. $500. Lasts two weeks.',
      },
      {
        textAr: 'رفض — الكرامة أهم',
        textEn: 'Refuse — dignity first',
        oneTimeCost: 0, monthlyCost: 0, workHoursLost: 0,
        healthEffect: -10, deathRisk: 0, injuryRisk: 0,
        moraleEffect: -10,
        burdenId: null, burdenLabelAr: '', burdenLabelEn: '',
        consequence: null,
        messageAr: 'رفضت. الجيب فارغ. لكن الكرامة باقية.',
        messageEn: 'Refused. Pocket empty. But dignity intact.',
      },
    ],
    autoEffect: null,
    showOnlyIfBroke: true,
    realFactAr: 'تجار السوق السوداء في غزة ضاعفوا أسعارهم 10-20 مرة خلال الحصار',
    realFactEn: 'Black market traders in Gaza raised prices 10-20x during the siege',
  },

  // ===== MONTH 17: Epidemic Diseases — Sanitation Costs =====
  {
    id: 'epidemic_sanitation',
    month: 17,
    recurring: true,
    autoEvent: false,
    titleAr: 'وباء — تكاليف الصرف الصحي',
    titleEn: 'Epidemic — Sanitation Costs',
    storyAr: 'التهاب الكبد الوبائي. الجرب. الكوليرا.\nمخيمات النازحين بلا صرف صحي.\nالوقاية الوحيدة: مياه معقمة ومنظفات.\n$250/شهر — أو المرض يجتاح الأسرة.',
    storyEn: 'Hepatitis. Scabies. Cholera.\nDisplacement camps with no sanitation.\nOnly prevention: sanitized water and disinfectants.\n$250/month — or disease sweeps the family.',
    choices: [
      {
        textAr: 'شراء منظفات ومياه معقمة ($250/شهر)',
        textEn: 'Buy disinfectants & clean water ($250/month)',
        oneTimeCost: 0, monthlyCost: 250, workHoursLost: 0,
        healthEffect: 0, deathRisk: 0, injuryRisk: 0,
        burdenId: 'sanitation', burdenLabelAr: 'صرف صحي', burdenLabelEn: 'Sanitation',
        consequence: null,
        messageAr: 'الحماية نسبية. الأمراض موجودة في كل مكان. لكنكم محميون بقدر الإمكان.',
        messageEn: 'Protection is relative. Disease is everywhere. But you\'re protected as much as possible.',
      },
      {
        textAr: 'امتناع — لا مال للوقاية',
        textEn: 'Skip — no money for prevention',
        oneTimeCost: 0, monthlyCost: 0, workHoursLost: 0,
        healthEffect: -15, deathRisk: 0.03, injuryRisk: 0,
        burdenId: null, burdenLabelAr: '', burdenLabelEn: '',
        consequence: null,
        messageAr: 'الأمراض تدخل. أعراض تبدأ. المستشفيات لا تعمل.',
        messageEn: 'Disease enters. Symptoms begin. Hospitals are not functioning.',
      },
    ],
    autoEffect: null,
    realFactAr: 'يوليو-أكتوبر 2024: 40,000 حالة التهاب كبد وبائي + تفشيات كوليرا وجرب في غزة',
    realFactEn: 'July-Oct 2024: 40,000 hepatitis cases + cholera and scabies outbreaks in Gaza',
  },

  // ===== MONTHS 18-24: Epidemic Sanitation recurring (auto-escalate) =====
  {
    id: 'epidemic_escalate_18',
    month: 18,
    recurring: false,
    autoEvent: true,
    titleAr: 'تصاعد تكاليف الوقاية',
    titleEn: 'Sanitation Costs Escalate',
    storyAr: 'أسعار المنظفات والمياه المعقمة تضاعفت.',
    storyEn: 'Disinfectant and sanitized water prices doubled.',
    choices: [],
    autoEffect: { updateBurdenId: 'sanitation', newAmount: 350 },
    realFactAr: 'نوفمبر 2024: غزة تعاني من نقص حاد في مواد التعقيم',
    realFactEn: 'November 2024: Gaza facing acute shortage of sanitation supplies',
  },
  {
    id: 'epidemic_escalate_21',
    month: 21,
    recurring: false,
    autoEvent: true,
    titleAr: 'تفاقم الأوبئة',
    titleEn: 'Epidemic Worsening',
    storyAr: 'الأوبئة تتفاقم. التكاليف ترتفع أكثر.',
    storyEn: 'Epidemics worsen. Costs rise further.',
    choices: [],
    autoEffect: { healthEffect: -8, updateBurdenId: 'sanitation', newAmount: 450 },
    realFactAr: 'ديسمبر 2024: أكثر من 500,000 حالة مرض جلدي معدٍ في مخيمات غزة',
    realFactEn: 'December 2024: Over 500,000 contagious skin disease cases in Gaza camps',
  },
  {
    id: 'starvation_deepens',
    month: 17,
    recurring: false,
    autoEvent: true,
    titleAr: 'تعمق المجاعة',
    titleEn: 'Famine Deepens',
    storyAr: 'أكتوبر 2024. IPC تصنف شمال غزة مجاعة رسمية.\nالمجاعة الأولى المُصنَّفة منذ عقود.',
    storyEn: 'October 2024. IPC classifies northern Gaza as official famine.\nFirst classified famine in decades.',
    choices: [],
    autoEffect: { healthEffect: -10 },
    realFactAr: 'أكتوبر 2024: IPC — المجاعة رسمية في شمال غزة لأول مرة',
    realFactEn: 'October 2024: IPC — Famine officially declared in northern Gaza for the first time',
  },
  {
    id: 'work_hazard_2',
    month: 18,
    recurring: false,
    autoEvent: true,
    titleAr: 'تصاعد خطر العمل',
    titleEn: 'Work Hazard Intensifies',
    storyAr: 'نوفمبر 2024. الاستهداف الممنهج لأصحاب المهن يتصاعد.',
    storyEn: 'November 2024. Systematic targeting of professionals escalates.',
    choices: [],
    autoEffect: { workingDeathRiskIncrease: 0.08 },
    realFactAr: 'نوفمبر 2024: 1,000+ عامل صحي استشهدوا في غزة',
    realFactEn: 'November 2024: 1,000+ healthcare workers martyred in Gaza',
  },
  {
    id: 'north_siege',
    month: 19,
    recurring: false,
    autoEvent: true,
    titleAr: 'الحصار الكامل على الشمال',
    titleEn: 'Complete Siege on North Gaza',
    storyAr: 'ديسمبر 2024. لا طعام ولا ماء يدخل شمال غزة.\nالطحين: $1,000 للكيس.',
    storyEn: 'December 2024. No food or water entering northern Gaza.\nFlour: $1,000 per bag.',
    choices: [],
    autoEffect: { northGazaFoodCostIncrease: 300, healthEffect: -10 },
    realFactAr: 'ديسمبر 2024: الأمم المتحدة — "مجاعة متعمدة" في شمال غزة',
    realFactEn: 'December 2024: UN — "Deliberate starvation" in northern Gaza',
  },
  {
    id: 'aid_blocked_20',
    month: 20,
    recurring: false,
    autoEvent: true,
    titleAr: 'إغلاق شبه كامل أمام المساعدات',
    titleEn: 'Near-Complete Aid Blockade',
    storyAr: 'يناير 2025. أقل من 60 شاحنة يومياً.\nكل الأسعار ترتفع 50%.',
    storyEn: 'January 2025. Under 60 trucks per day.\nAll prices rise 50%.',
    choices: [],
    autoEffect: { allBurdenIncrease: 0.50 },
    realFactAr: 'يناير 2025: وصول المساعدات أدنى مستوى — 60 شاحنة/يوم مقابل 500 قبل الحرب',
    realFactEn: 'January 2025: Aid at lowest point — 60 trucks/day vs 500 pre-war',
  },
  {
    id: 'currency_collapse',
    month: 21,
    recurring: false,
    autoEvent: true,
    titleAr: 'انهيار قيمة المال',
    titleEn: 'Currency / Savings Devaluation',
    storyAr: 'فبراير 2025. ما تبقى في يدك من نقود خسر 20% من قيمته.',
    storyEn: 'February 2025. Whatever cash you have lost 20% of its value.',
    choices: [],
    autoEffect: { savingsDevaluation: 0.20 },
    realFactAr: 'فبراير 2025: انهيار القوة الشرائية في غزة — التضخم بآلاف النسب المئوية',
    realFactEn: 'February 2025: Collapse of purchasing power in Gaza — inflation in thousands of percent',
  },
  {
    id: 'ceasefire_rumor',
    month: 22,
    recurring: false,
    autoEvent: true,
    titleAr: 'إشاعة الهدنة — ثم الانهيار',
    titleEn: 'Ceasefire Rumor — Then Collapse',
    storyAr: 'مارس 2025. الراديو يقول: هدنة قريبة.\nبعد 3 أيام: انهيار المفاوضات. القصف يتضاعف.',
    storyEn: 'March 2025. Radio says: ceasefire soon.\n3 days later: negotiations collapse. Bombing doubles.',
    choices: [],
    autoEffect: { moraleBonusThenPenalty: { bonus: 15, penalty: -25 } },
    realFactAr: 'مارس 2025: انهيار محادثات الهدنة مرات متعددة',
    realFactEn: 'March 2025: Ceasefire talks collapsed multiple times',
  },
  {
    id: 'wck_aftermath',
    month: 23,
    recurring: false,
    autoEvent: true,
    titleAr: 'انسحاب منظمات الإغاثة',
    titleEn: 'Aid Organizations Withdraw',
    storyAr: 'أبريل 2025. بعد مقتل عمال الإغاثة — المنظمات الإنسانية تعلق عملياتها.\nتوقف الوجبات الجاهزة والمطابخ الميدانية.',
    storyEn: 'April 2025. After aid workers killed — humanitarian organizations suspend operations.\nReady meals and field kitchens stop.',
    choices: [],
    autoEffect: { foodCostIncrease: 200, durationMonths: 2 },
    realFactAr: 'مقتل 7 من مطبخ العالم المركزي أفضى لتعليق عمليات المنظمة مؤقتاً',
    realFactEn: 'WCK killing of 7 workers led to temporary suspension of operations',
  },
  {
    id: 'partial_aid_resume',
    month: 24,
    recurring: false,
    autoEvent: true,
    titleAr: 'عودة جزئية للمساعدات',
    titleEn: 'Partial Aid Resumes',
    storyAr: 'مايو 2025. بعد ضغوط دولية، وصل قدر محدود من المساعدات.\n$500 قيمة مواد إغاثة.',
    storyEn: 'May 2025. After international pressure, limited aid arrived.\n$500 worth of relief supplies.',
    choices: [],
    autoEffect: { savingsBonus: 500 },
    realFactAr: 'مايو 2025: عودة محدودة للمساعدات بعد ضغوط دولية مكثفة',
    realFactEn: 'May 2025: Limited aid resumed after intense international pressure',
  },

  // ===== MONTH 25: Internet / Telecom Cutoff =====
  {
    id: 'internet_cutoff',
    month: 25,
    recurring: true,
    autoEvent: false,
    titleAr: 'انقطاع الاتصالات التام',
    titleEn: 'Total Communications Blackout',
    storyAr: 'يونيو 2025. الإنترنت قُطع كلياً.\nلا تعرف شيئاً عن أقاربك في مكان آخر.\nلا تعرف إن كانوا أحياء.\nالعزلة: سلاح آخر.',
    storyEn: 'June 2025. Internet completely cut.\nYou know nothing about relatives elsewhere.\nDon\'t know if they are alive.\nIsolation: another weapon.',
    choices: [
      {
        textAr: 'شراء eSIM خارجي ($150/شهر)',
        textEn: 'Buy foreign eSIM ($150/month)',
        oneTimeCost: 0, monthlyCost: 150, workHoursLost: 0,
        healthEffect: 0, deathRisk: 0, injuryRisk: 0,
        moraleEffect: 10,
        burdenId: 'esim', burdenLabelAr: 'شريحة إنترنت', burdenLabelEn: 'eSIM',
        consequence: null,
        messageAr: 'تواصلت. أقاربك على قيد الحياة. هذا الخبر يستحق كل دولار.',
        messageEn: 'Connected. Your relatives are alive. This news is worth every dollar.',
      },
      {
        textAr: 'الامتناع — عزلة تامة',
        textEn: 'Skip — total isolation',
        oneTimeCost: 0, monthlyCost: 0, workHoursLost: 0,
        healthEffect: 0, deathRisk: 0, injuryRisk: 0,
        moraleEffect: -25,
        burdenId: null, burdenLabelAr: '', burdenLabelEn: '',
        consequence: null,
        messageAr: 'صمت مطبق. لا أخبار. لا تعرف إن كانوا أحياء.',
        messageEn: 'Deathly silence. No news. Don\'t know if they\'re alive.',
      },
    ],
    autoEffect: null,
    realFactAr: 'غزة 2024-2025: قطع متكرر للإنترنت — أطول انقطاع 12 يوماً',
    realFactEn: 'Gaza 2024-2025: Repeated internet blackouts — longest blackout 12 days',
  },

  // ===== MONTHS 26-35: Price Frenzy (saar al-as'ar) =====
  {
    id: 'price_frenzy_26',
    month: 26,
    recurring: false,
    autoEvent: true,
    titleAr: 'سعار الأسعار — كل شيء يتضاعف',
    titleEn: 'Price Frenzy — Everything Doubles',
    storyAr: 'يوليو 2025.\nأمراء الحرب يتحكمون في كل شيء.\nكل أعبائك الشهرية ارتفعت 50% إضافية.',
    storyEn: 'July 2025.\nWarlords control everything.\nAll your monthly burdens rose 50% more.',
    choices: [],
    autoEffect: { allBurdenIncrease: 0.50 },
    realFactAr: 'غزة 2025: سيطرة شبكات مافيا الحرب على توزيع البضائع في القطاع',
    realFactEn: 'Gaza 2025: War mafia networks controlling goods distribution in the Strip',
  },
  {
    id: 'price_frenzy_28',
    month: 28,
    recurring: false,
    autoEvent: true,
    titleAr: 'ضربة مخيم خيام',
    titleEn: 'Tent Camp Strike',
    storyAr: 'أغسطس 2025. ضربة مباشرة على مخيم خيام.\n21 خيمة احترقت في الليل.',
    storyEn: 'August 2025. Direct strike on tent camp.\n21 tents burned overnight.',
    choices: [],
    autoEffect: { deathRisk: 0.15, injuryRisk: 0.20 },
    realFactAr: 'ديسمبر 2024: 7 ضربات على مخيمات الخيام في أسبوعين — 34 قتيلاً منهم 10 أطفال',
    realFactEn: 'December 2024: 7 strikes on tent camps in two weeks — 34 killed including 10 children',
  },
  {
    id: 'malnutrition_peak',
    month: 29,
    recurring: false,
    autoEvent: true,
    titleAr: 'ذروة سوء التغذية',
    titleEn: 'Peak Malnutrition',
    storyAr: 'سبتمبر 2025.\nالأجسام تأكل نفسها.\nسوء التغذية الحاد الوخيم — أطفال ينهارون.',
    storyEn: 'September 2025.\nBodies are consuming themselves.\nSevere acute malnutrition — children collapsing.',
    choices: [],
    autoEffect: { healthEffect: -20 },
    realFactAr: 'WHO 2024: كل طفل تحت 5 سنوات في شمال غزة مصاب بسوء التغذية الحاد',
    realFactEn: 'WHO 2024: Every child under 5 in northern Gaza suffering acute malnutrition',
  },
  {
    id: 'price_frenzy_30',
    month: 30,
    recurring: false,
    autoEvent: true,
    titleAr: 'شتاء ثانٍ بلا مأوى',
    titleEn: 'Second Winter Without Shelter',
    storyAr: 'أكتوبر 2025. الشتاء الثاني في الخيام.\nبرد. مرض. أطفال بلا دفء.',
    storyEn: 'October 2025. Second winter in tents.\nCold. Illness. Children without warmth.',
    choices: [],
    autoEffect: { healthEffect: -15, allBurdenIncrease: 0.30 },
    realFactAr: 'شتاء 2024-2025: وفاة أطفال من البرد في خيام غزة',
    realFactEn: 'Winter 2024-2025: Children died from cold in Gaza tents',
  },
  {
    id: 'negotiations_31',
    month: 31,
    recurring: false,
    autoEvent: true,
    titleAr: 'مفاوضات الهدنة تتجدد',
    titleEn: 'Ceasefire Negotiations Resumed',
    storyAr: 'نوفمبر 2025. مفاوضات جديدة.\nالعالم يتحدث. غزة تنزف.',
    storyEn: 'November 2025. New negotiations.\nThe world talks. Gaza bleeds.',
    choices: [],
    autoEffect: { moraleEffect: 5 },
    realFactAr: 'نوفمبر-ديسمبر 2025: جولات متعددة من المفاوضات بوساطة قطر ومصر',
    realFactEn: 'Nov-Dec 2025: Multiple negotiation rounds mediated by Qatar and Egypt',
  },
  {
    id: 'partial_ceasefire_32',
    month: 32,
    recurring: false,
    autoEvent: true,
    titleAr: 'تخفيف جزئي',
    titleEn: 'Partial Reduction',
    storyAr: 'ديسمبر 2025. بعض المساعدات تصل.\nالأسعار تنخفض 20%.',
    storyEn: 'December 2025. Some aid reaches you.\nPrices decrease 20%.',
    choices: [],
    autoEffect: { allBurdenDecrease: 0.20, savingsBonus: 300 },
    realFactAr: 'ديسمبر 2025: زيادة طفيفة في المساعدات بعد ضغوط دبلوماسية',
    realFactEn: 'December 2025: Slight aid increase after diplomatic pressure',
  },
  {
    id: 'return_blocked_33',
    month: 33,
    recurring: false,
    autoEvent: false,
    titleAr: 'محاولة العودة — الحاجز يطلق النار',
    titleEn: 'Return Attempt — Checkpoint Opens Fire',
    storyAr: 'يناير 2026. سمعت أن الوضع في الشمال تحسّن.\nحاولت العودة لحيّك.\nالحاجز أطلق النار.',
    storyEn: 'January 2026. Heard things improved in the north.\nYou tried to return to your neighborhood.\nCheckpoint opened fire.',
    choices: [
      {
        textAr: 'حاول العودة',
        textEn: 'Attempt return',
        oneTimeCost: 0, monthlyCost: 0, workHoursLost: 0,
        healthEffect: -15, deathRisk: 0.08, injuryRisk: 0.12,
        burdenId: null, burdenLabelAr: '', burdenLabelEn: '',
        consequence: null,
        messageAr: 'انتهت المحاولة بجروح. العودة مستحيلة.',
        messageEn: 'Attempt ended in injuries. Return is impossible.',
      },
      {
        textAr: 'ابقَ — لا يستحق الخطر',
        textEn: 'Stay — not worth the risk',
        oneTimeCost: 0, monthlyCost: 0, workHoursLost: 0,
        healthEffect: 0, deathRisk: 0, injuryRisk: 0,
        moraleEffect: -15,
        burdenId: null, burdenLabelAr: '', burdenLabelEn: '',
        consequence: null,
        messageAr: 'بقيت. البيت هناك. أنت هنا. المسافة لا تُقاس بالكيلومترات.',
        messageEn: 'Stayed. Home is there. You are here. Distance can\'t be measured in kilometers.',
      },
    ],
    autoEffect: null,
    realFactAr: 'أبريل 2024: جنود أطلقوا النار على حشود تحاول العودة للشمال — سقطت فتاة صغيرة',
    realFactEn: 'April 2024: Soldiers fired on crowds attempting to return north — a young girl was killed',
  },
  {
    id: 'ceasefire_jan_2026',
    month: 34,
    recurring: false,
    autoEvent: true,
    titleAr: 'وقف إطلاق النار — الصمت',
    titleEn: 'Ceasefire — The Silence',
    storyAr: 'فبراير 2026.\n\nصمت.\n\nبعد أكثر من عامين.\n\nصمت حقيقي.',
    storyEn: 'February 2026.\n\nSilence.\n\nAfter more than two years.\n\nReal silence.',
    choices: [],
    autoEffect: { salaryRestore: 0.30, allBurdenDecrease: 0.30, moraleEffect: 20, savingsBonus: 500 },
    realFactAr: 'يناير 2025: وقف إطلاق النار الأول — 376,000 نازح بدأوا العودة شمالاً',
    realFactEn: 'January 2025: First ceasefire — 376,000 displaced began returning north',
  },
  {
    id: 'return_to_rubble',
    month: 35,
    recurring: false,
    autoEvent: true,
    titleAr: 'العودة إلى الركام',
    titleEn: 'Returning to Rubble',
    storyAr: 'مارس 2026. وصلت لحيّك.\n\nالبيت... غير موجود.\nالشارع... غير موجود.\nالمسجد... غير موجود.\n\nكل شيء ركام.',
    storyEn: 'March 2026. You reached your neighborhood.\n\nThe house... gone.\nThe street... gone.\nThe mosque... gone.\n\nEverything is rubble.',
    choices: [],
    autoEffect: { moraleEffect: -30 },
    realFactAr: 'سبتمبر 2024: 66% من مباني غزة تضررت — $18.5 مليار خسائر = 97% من الناتج المحلي',
    realFactEn: 'September 2024: 66% of Gaza buildings damaged — $18.5B losses = 97% of GDP',
  },

  // ===== MONTH 36: Final Count =====
  {
    id: 'final_count',
    month: 36,
    recurring: false,
    autoEvent: true,
    titleAr: 'النهاية — الإحصاء الأخير',
    titleEn: 'The End — Final Count',
    storyAr: 'أبريل 2026.\n27 شهراً من الحرب.\nمن نجا من عائلتك؟\nماذا بقي من حياتكم؟',
    storyEn: 'April 2026.\n27 months of war.\nWho survived from your family?\nWhat is left of your lives?',
    choices: [],
    autoEffect: { triggerEndGame: true },
    realFactAr: 'غزة 2026: أكثر من 55,000 شهيد. مليون وثمانمائة ألف نازح. مجاعة متواصلة.',
    realFactEn: 'Gaza 2026: Over 55,000 martyred. 1.8 million displaced. Ongoing famine.',
  },
];
