// monthly_challenges.js - 36-month scripted events for Gaza war simulation
// Oct 2023 (month 1) through Jan 2026 (month 36)

const MONTHLY_CHALLENGES = [

  // ===== MONTH 1: First Displacement =====
  {
    id: 'displacement_1',
    month: 1,
    recurring: true,
    autoEvent: false,
    titleAr: 'النزوح الأول',
    titleEn: 'First Displacement',
    storyAr: 'أكتوبر 2023. أوامر الإخلاء تصدر. الحي يفرغ حولك.\n1.1 مليون شخص يواجهون نفس القرار.\nماذا تفعل؟',
    storyEn: 'October 2023. Evacuation orders issued. The neighborhood empties around you.\n1.1 million people face the same decision.\nWhat do you do?',
    choices: [
      {
        textAr: 'مشي على الأقدام (مجاناً)',
        textEn: 'Walk on foot (free)',
        oneTimeCost: 0,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -20,
        deathRisk: 0.05,
        injuryRisk: 0,
        burdenId: 'shelter_walk',
        burdenLabelAr: 'إيجار خيمة وأفرشة',
        burdenLabelEn: 'Tent & bedding rental',
        shelterSetupCost: 3000,
        consequence: null,
        messageAr: 'مشيتم ساعات. الطريق مكتظ. بعض الأسر لم تصل.',
        messageEn: 'You walked for hours. The road was crowded. Some families never arrived.',
      },
      {
        textAr: 'شاحنة نقل ($1,500)',
        textEn: 'Hire a truck ($1,500)',
        oneTimeCost: 1500,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'shelter_truck',
        burdenLabelAr: 'إيجار خيمة',
        burdenLabelEn: 'Tent rental',
        shelterSetupCost: 1000,
        consequence: null,
        messageAr: 'ركبتم شاحنة. وصلتم. الخيمة تنتظر.',
        messageEn: 'You rode a truck. You arrived. The tent awaits.',
      },
      {
        textAr: 'البقاء في البيت (خطر شديد)',
        textEn: 'Stay home (very dangerous)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0.15,
        injuryRisk: 0.20,
        captureRisk: 0.10,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'stay_dangerous',
        messageAr: 'بقيتم. القصف يشتد. الجيران غادروا. أنتم وحدكم.',
        messageEn: 'You stayed. The bombing intensified. The neighbors left. You are alone.',
      },
    ],
    autoEffect: null,
    realFactAr: 'أكتوبر 2023: أُمر 1.1 مليون شخص بالإخلاء خلال 24 ساعة',
    realFactEn: 'October 2023: 1.1 million people ordered to evacuate within 24 hours',
  },

  // ===== MONTH 2: Water Crisis =====
  {
    id: 'water_crisis',
    month: 2,
    recurring: true,
    autoEvent: false,
    titleAr: 'انقطاع المياه',
    titleEn: 'Water Crisis',
    storyAr: 'نوفمبر 2023. شبكة المياه توقفت.\n94% انخفاض في إمدادات المياه.\nالأطفال يحصلون على 1.5 لتر في اليوم.',
    storyEn: 'November 2023. The water network has stopped.\n94% drop in water supply.\nChildren receive 1.5 liters per day.',
    choices: [
      {
        textAr: 'شراء مياه ($300/شهر)',
        textEn: 'Buy water ($300/month)',
        oneTimeCost: 0,
        monthlyCost: 300,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'water_purchase',
        burdenLabelAr: 'شراء مياه',
        burdenLabelEn: 'Water purchase',
        consequence: null,
        messageAr: 'تشترون المياه بسعر الحرب. مكلف لكنه ضروري.',
        messageEn: 'You buy water at war prices. Expensive but necessary.',
      },
      {
        textAr: 'تعبئة يدوية من مصادر بعيدة (3 ساعات/يوم)',
        textEn: 'Manual collection from distant sources (3 hours/day)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 3,
        healthEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'تمشون كيلومترات لجلب المياه. متعب جداً.',
        messageEn: 'You walk kilometers to collect water. Exhausting.',
      },
      {
        textAr: 'الاستغناء عن المياه النظيفة (خطر صحي)',
        textEn: 'Go without clean water (health risk)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -20,
        diseaseRisk: 0.15,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'بلا مياه نظيفة. الأمراض تبدأ تظهر.',
        messageEn: 'Without clean water. Diseases begin to appear.',
      },
    ],
    autoEffect: null,
    realFactAr: 'نوفمبر 2023: 94% انخفاض في إمدادات المياه — الأطفال يحصلون على 1.5 لتر/يوم',
    realFactEn: 'November 2023: 94% drop in water supply — children received 1.5L/day',
  },

  // ===== MONTH 2: Power/Internet Outage =====
  {
    id: 'power_outage',
    month: 2,
    recurring: true,
    autoEvent: false,
    titleAr: 'انقطاع الكهرباء والإنترنت',
    titleEn: 'Power & Internet Cut',
    storyAr: 'الكهرباء انقطعت منذ الأسابيع الأولى.\nالإنترنت متقطع. لا تواصل مع العالم.\nكيف تتعامل مع الظلام؟',
    storyEn: 'Electricity has been cut since the first weeks.\nInternet is sporadic. No contact with the world.\nHow do you deal with the darkness?',
    choices: [
      {
        textAr: 'شراء مولّد كهرباء ($3,000 مرة واحدة)',
        textEn: 'Buy a generator ($3,000 one-time)',
        oneTimeCost: 3000,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'اشتريتم مولداً. الكهرباء عادت جزئياً. ترف نسبي.',
        messageEn: 'You bought a generator. Electricity returned partially.',
      },
      {
        textAr: 'شراء ساعات محدودة من التجار ($100/شهر)',
        textEn: 'Buy limited hours from vendors ($100/month)',
        oneTimeCost: 0,
        monthlyCost: 100,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'power_vendor',
        burdenLabelAr: 'كهرباء التجار',
        burdenLabelEn: 'Vendor electricity',
        consequence: null,
        messageAr: 'ساعات قليلة من الكهرباء تكفي للأساسيات.',
        messageEn: 'A few hours of electricity for basics.',
      },
      {
        textAr: 'الاستغناء التام عن الكهرباء',
        textEn: 'Go completely without power',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 1,
        healthEffect: 0,
        moraleEffect: -10,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'الظلام يطول. المعنويات تهبط. لكن المال يُوفّر.',
        messageEn: 'The darkness grows. Morale drops. But money is saved.',
      },
    ],
    autoEffect: null,
    realFactAr: 'انقطعت الكهرباء عن غزة بالكامل منذ أكتوبر 2023',
    realFactEn: 'Gaza lost all electricity from October 2023',
  },

  // ===== MONTH 3: Potable Water Shortage =====
  {
    id: 'potable_water',
    month: 3,
    recurring: true,
    autoEvent: false,
    titleAr: 'نقص مياه الشرب النقية',
    titleEn: 'Potable Water Shortage',
    storyAr: 'ديسمبر 2023. حتى المياه المشتراة أصبحت ملوثة.\nتحتاج إلى مياه نقية للشرب والطهي.',
    storyEn: 'December 2023. Even purchased water is becoming contaminated.\nYou need clean water for drinking and cooking.',
    choices: [
      {
        textAr: 'شراء مياه نقية معبأة ($100/شهر)',
        textEn: 'Buy bottled clean water ($100/month)',
        oneTimeCost: 0,
        monthlyCost: 100,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'potable_water',
        burdenLabelAr: 'مياه الشرب النقية',
        burdenLabelEn: 'Bottled drinking water',
        consequence: null,
        messageAr: 'مياه نظيفة. أغلى لكن أأمن.',
        messageEn: 'Clean water. More expensive but safer.',
      },
      {
        textAr: 'جمع المياه يدوياً من نقاط التوزيع',
        textEn: 'Collect manually from distribution points',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 3,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'تنتظرون ساعات في الطابور. مضنٍ لكن مجاني.',
        messageEn: 'You wait hours in line. Exhausting but free.',
      },
      {
        textAr: 'استخدام المياه المتاحة (خطر أمراض)',
        textEn: 'Use available water (disease risk)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -15,
        diseaseRisk: 0.20,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'مياه غير آمنة. المعدة تُعاني.',
        messageEn: 'Unsafe water. Stomach problems begin.',
      },
    ],
    autoEffect: null,
    realFactAr: 'ديسمبر 2023: تلوث 70% من مصادر المياه الجوفية',
    realFactEn: 'December 2023: 70% of groundwater sources contaminated',
  },

  // ===== MONTH 4: Banking Crisis (Auto) =====
  {
    id: 'banking_crisis_1',
    month: 4,
    recurring: false,
    autoEvent: true,
    titleAr: 'أزمة السيولة المصرفية',
    titleEn: 'Banking Crisis',
    storyAr: 'يناير 2024. البنوك أغلقت. تدفع 10% لسحب راتبك.\nهذه التكلفة مؤلمة لكنك لا تملك خياراً.',
    storyEn: 'January 2024. Banks closed. You pay 10% to withdraw your salary.\nThis cost is painful but you have no choice.',
    choices: [],
    autoEffect: { salaryPenaltyAdd: 0.10 },
    realFactAr: 'أغلقت بنوك غزة — العمال يدفعون 10-30% عمولة لصرافين غير رسميين',
    realFactEn: 'Gaza banks closed completely — workers paid 10-30% fees to unlicensed money changers',
  },

  // ===== MONTH 5: Coffee/Beverages Shortage =====
  {
    id: 'beverages_shortage',
    month: 5,
    recurring: false,
    autoEvent: false,
    titleAr: 'نقص القهوة والمشروبات',
    titleEn: 'Coffee & Beverages Shortage',
    storyAr: 'فبراير 2024. البضائع الأساسية نفدت من الأسواق.\nالقهوة والشاي أصبحا رفاهية.\nصغيرة لكنها تعني الكثير.',
    storyEn: 'February 2024. Basic goods have run out of markets.\nCoffee and tea have become luxuries.\nSmall but it means a lot.',
    choices: [
      {
        textAr: 'شراء من السوق السوداء ($100/شهر)',
        textEn: 'Buy from black market ($100/month)',
        oneTimeCost: 0,
        monthlyCost: 100,
        workHoursLost: 0,
        healthEffect: 0,
        moraleEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'beverages',
        burdenLabelAr: 'مشروبات',
        burdenLabelEn: 'Beverages',
        consequence: null,
        messageAr: 'فنجان قهوة في الحرب. يكفي للاستمرار.',
        messageEn: 'A cup of coffee in war. Enough to keep going.',
      },
      {
        textAr: 'الامتناع التام',
        textEn: 'Go without entirely',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        moraleEffect: -8,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'تصبرون. الأموال محدودة. المعنويات تتراجع قليلاً.',
        messageEn: 'You endure. Money is limited. Morale drops slightly.',
      },
    ],
    autoEffect: null,
    realFactAr: 'أسعار السلع الأساسية ارتفعت 400% في غزة بداية 2024',
    realFactEn: 'Basic goods prices rose 400% in Gaza by early 2024',
  },

  // ===== MONTH 6: Cooking Gas Shortage =====
  {
    id: 'cooking_gas',
    month: 6,
    recurring: true,
    autoEvent: false,
    titleAr: 'نقص غاز الطهي',
    titleEn: 'Cooking Gas Shortage',
    storyAr: 'مارس 2024. الغاز المنزلي انتهى.\nالطبخ أصبح مشكلة يومية.\nكيف تُطعم عائلتك؟',
    storyEn: 'March 2024. Domestic gas has run out.\nCooking has become a daily problem.\nHow do you feed your family?',
    choices: [
      {
        textAr: 'شراء غاز بسعر الحرب ($300/شهر)',
        textEn: 'Buy gas at war price ($300/month)',
        oneTimeCost: 0,
        monthlyCost: 300,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'cooking_gas',
        burdenLabelAr: 'غاز الطهي',
        burdenLabelEn: 'Cooking gas',
        consequence: null,
        messageAr: 'غاز بسعر خيالي. لكن الطعام يُطهى.',
        messageEn: 'Gas at an outrageous price. But food gets cooked.',
      },
      {
        textAr: 'الطهي على الأخشاب ($100/شهر)',
        textEn: 'Cook on wood fire ($100/month)',
        oneTimeCost: 0,
        monthlyCost: 100,
        workHoursLost: 0,
        healthEffect: -3,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'wood_cooking',
        burdenLabelAr: 'أخشاب للطهي',
        burdenLabelEn: 'Firewood cooking',
        consequence: null,
        messageAr: 'نار الأخشاب. أقل تكلفة. الدخان يزعج الأطفال.',
        messageEn: 'Wood fire. Less cost. Smoke bothers the children.',
      },
      {
        textAr: 'أكل بارد وطعام خام',
        textEn: 'Eat cold and raw food',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -10,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'طعام بارد وخام. الصحة تتراجع.',
        messageEn: 'Cold and raw food. Health deteriorates.',
      },
    ],
    autoEffect: null,
    realFactAr: 'غزة 2024: غاز الطهي اختفى تماماً — السكان يحرقون الخشب والبلاستيك',
    realFactEn: 'Gaza 2024: Cooking gas disappeared — residents burning wood and plastic',
  },

  // ===== MONTH 6: Vegetables/Fruits Shortage =====
  {
    id: 'vegetables_shortage',
    month: 6,
    recurring: true,
    autoEvent: false,
    titleAr: 'اختفاء الخضار والفواكه',
    titleEn: 'Vegetables & Fruits Disappear',
    storyAr: 'الأسواق فارغة من الخضار والفواكه.\nسوء التغذية يبدأ يظهر على الأطفال.',
    storyEn: 'Markets are empty of vegetables and fruits.\nMalnutrition starts to show in children.',
    choices: [
      {
        textAr: 'شراء من التجار ($200/شهر)',
        textEn: 'Buy from traders ($200/month)',
        oneTimeCost: 0,
        monthlyCost: 200,
        workHoursLost: 0,
        healthEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'vegetables',
        burdenLabelAr: 'خضار وفواكه',
        burdenLabelEn: 'Vegetables & fruits',
        consequence: null,
        messageAr: 'خضار بأسعار مبالغ فيها. لكن الأطفال يأكلون.',
        messageEn: 'Vegetables at inflated prices. But the children eat.',
      },
      {
        textAr: 'الاستغناء (نقص غذائي)',
        textEn: 'Go without (nutritional deficiency)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -8,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'بلا خضار. سوء التغذية يتراكم.',
        messageEn: 'Without vegetables. Malnutrition accumulates.',
      },
    ],
    autoEffect: null,
    realFactAr: 'ربيع 2024: 100% من سكان غزة يعانون من انعدام الأمن الغذائي',
    realFactEn: 'Spring 2024: 100% of Gaza population experiencing food insecurity',
  },

  // ===== MONTH 6: Emigration Option =====
  {
    id: 'emigration_window',
    month: 6,
    recurring: false,
    autoEvent: false,
    titleAr: 'فرصة السفر والهجرة',
    titleEn: 'Emigration Window',
    storyAr: 'مارس 2024. فُتح باب السفر لمن يملك المال.\nتذاكر وإجراءات ورشاوى. المجموع: $30,000.\nإما الرحيل أو البقاء في الإبادة.',
    storyEn: 'March 2024. The door of travel opened for those with money.\nTickets, procedures, bribes. Total: $30,000.\nLeave or stay in the genocide.',
    choices: [
      {
        textAr: 'السفر مع الأسرة كاملة ($30,000)',
        textEn: 'Leave with the whole family ($30,000)',
        oneTimeCost: 30000,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'emigrate',
        messageAr: 'غادرتم. نجوتم بأرواحكم. البيت... لن يعود.',
        messageEn: 'You left. You survived with your lives. The home... will never return.',
      },
      {
        textAr: 'البقاء — هذه أرضنا',
        textEn: 'Stay — this is our land',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'stay_dangerous',
        messageAr: 'قررتم البقاء. هذا اختياركم. هذه أرضكم.',
        messageEn: 'You decided to stay. This is your choice. This is your land.',
      },
    ],
    autoEffect: null,
    realFactAr: 'كلف السفر لمصر عبر رفح ما بين $5,000 و$30,000 للأسرة الواحدة',
    realFactEn: 'Travel to Egypt through Rafah cost between $5,000 and $30,000 per family',
  },

  // ===== MONTH 7: Second Displacement =====
  {
    id: 'displacement_2',
    month: 7,
    recurring: true,
    autoEvent: false,
    titleAr: 'النزوح الثاني',
    titleEn: 'Second Displacement',
    storyAr: 'يناير 2024. أوامر إخلاء جديدة.\nهذه المرة من مكان النزوح الأول.\nخسرتم كل شيء مرة. والآن مرة أخرى.',
    storyEn: 'January 2024. New evacuation orders.\nThis time from the first displacement site.\nYou lost everything once. And now again.',
    choices: [
      {
        textAr: 'مشي على الأقدام (مجاناً)',
        textEn: 'Walk on foot (free)',
        oneTimeCost: 0,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -20,
        deathRisk: 0.05,
        injuryRisk: 0,
        burdenId: 'shelter_walk_2',
        burdenLabelAr: 'إيجار خيمة ثانية',
        burdenLabelEn: 'Second tent rental',
        shelterSetupCost: 2000,
        consequence: null,
        messageAr: 'نزوح ثانٍ. الجسم أنهكه المشي. لكنكم وصلتم.',
        messageEn: 'Second displacement. The body is exhausted from walking. But you arrived.',
      },
      {
        textAr: 'شاحنة نقل ($1,500)',
        textEn: 'Hire a truck ($1,500)',
        oneTimeCost: 1500,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'shelter_truck_2',
        burdenLabelAr: 'إيجار خيمة ثانية',
        burdenLabelEn: 'Second tent rental',
        shelterSetupCost: 1000,
        consequence: null,
        messageAr: 'مرة ثانية في الشاحنة. أين تنتهي هذه الرحلة؟',
        messageEn: 'A second time in the truck. Where does this journey end?',
      },
      {
        textAr: 'البقاء مجدداً (خطر شديد جداً)',
        textEn: 'Stay again (extremely dangerous)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0.20,
        injuryRisk: 0.25,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'stay_dangerous',
        messageAr: 'بقيتم مجدداً. الخطر أضعاف ما كان. القصف في كل مكان.',
        messageEn: 'You stayed again. The danger is multiple times worse. Bombing everywhere.',
      },
    ],
    autoEffect: null,
    realFactAr: 'يناير 2024: النازحون في غزة يُنزحون مرة أخرى وثالثة ورابعة',
    realFactEn: 'January 2024: Displaced Gazans were displaced again and again',
  },

  // ===== MONTH 8: Aid Convoy =====
  {
    id: 'aid_convoy',
    month: 8,
    recurring: false,
    autoEvent: false,
    titleAr: 'قوافل المساعدات الأمريكية',
    titleEn: 'US Aid Convoy Run',
    storyAr: 'فبراير 2024. قوافل مساعدات أمريكية تصل.\nإذا ذهبت تستطيع الحصول على مؤن — لكن المخاطر حقيقية.\n112 شهيداً سقطوا في مجزرة الدقيق بنفس الطريقة.',
    storyEn: 'February 2024. US aid convoys arrive.\nIf you go you can get supplies — but the risks are real.\n112 killed in the Flour Massacre the same way.',
    choices: [
      {
        textAr: 'اذهب للمساعدات (+$1,000)',
        textEn: 'Go for the aid (+$1,000)',
        oneTimeCost: -1000,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0.10,
        injuryRisk: 0.20,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'ذهبت. الخطر حقيقي. بعض من ذهبوا لم يعودوا.',
        messageEn: 'You went. The danger is real. Some who went never returned.',
      },
      {
        textAr: 'امتنع — الأمان أهم',
        textEn: 'Refuse — safety first',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'قررت البقاء. أسرتك آمنة. لكن الطعام شحيح.',
        messageEn: 'You decided to stay. Your family is safe. But food is scarce.',
      },
    ],
    autoEffect: null,
    realFactAr: '29 فبراير 2024: مجزرة الدقيق — 112 شهيداً، 750 جريحاً عند نقطة توزيع المساعدات',
    realFactEn: 'Feb 29, 2024: Flour Massacre — 112 killed, 750 wounded at aid distribution point',
    showOnlyIfBroke: true,
  },

  // ===== MONTH 9: Baby Formula =====
  {
    id: 'baby_formula',
    month: 9,
    recurring: true,
    autoEvent: false,
    titleAr: 'حليب الأطفال الرضّع',
    titleEn: 'Baby Formula',
    storyAr: 'أبريل 2024. الأطفال الرضّع بحاجة لحليب صناعي.\nقبل الحرب: $15. الآن: $200.\nطفلك يبكي جوعاً.',
    storyEn: 'April 2024. Infants need baby formula.\nBefore the war: $15. Now: $200.\nYour baby cries from hunger.',
    choices: [
      {
        textAr: 'شراء حليب الأطفال ($200/شهر)',
        textEn: 'Buy baby formula ($200/month)',
        oneTimeCost: 0,
        monthlyCost: 200,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'baby_formula',
        burdenLabelAr: 'حليب الأطفال',
        burdenLabelEn: 'Baby formula',
        consequence: null,
        messageAr: '$200 لزجاجة حليب. أغلى شيء في الحرب: أن يأكل طفلك.',
        messageEn: '$200 for a bottle of milk. The most expensive thing in war: your child eating.',
      },
      {
        textAr: 'لا يمكن الشراء (صحة الأطفال تتراجع)',
        textEn: 'Cannot afford (children health declines)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -15,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        childrenOnly: true,
        consequence: null,
        messageAr: 'الطفل يبكي. لا يوجد حليب. الوزن ينخفض.',
        messageEn: 'The baby cries. No milk. Weight is dropping.',
      },
    ],
    autoEffect: null,
    realFactAr: 'أبريل 2024: أسعار حليب الأطفال ارتفعت 1200% — وفيات رضّع من الجوع',
    realFactEn: 'April 2024: Baby formula prices rose 1200% — infant deaths from starvation',
    showOnlyIfChildren: true,
  },

  // ===== MONTH 9: Neighbor's Plea =====
  {
    id: 'neighbor_formula',
    month: 9,
    recurring: false,
    autoEvent: false,
    titleAr: 'الجار يطرق الباب',
    titleEn: "Neighbor's Plea",
    storyAr: 'طرق الباب رجل يحمل طفله الرضيع.\n"ابني لم يأكل منذ يومين. عندك حليب؟"\nنظراته يائسة.',
    storyEn: 'A man knocked at the door carrying his infant.\n"My son hasn\'t eaten in two days. Do you have formula?"\nHis eyes are desperate.',
    choices: [
      {
        textAr: 'أعطيه من مخزونك ($200)',
        textEn: 'Give him from your stock ($200)',
        oneTimeCost: 200,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        moraleEffect: 15,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'أعطيته. قال "الله يحفظ أولادك". هذا يساوي كل شيء.',
        messageEn: 'You gave it. He said "God protect your children." That is worth everything.',
      },
      {
        textAr: 'تعتذر — لا يكفيك أنت',
        textEn: 'Apologize — not enough for yourself',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        moraleEffect: -20,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'غلقت الباب. صرخة الطفل تطاردك في نومك.',
        messageEn: 'You closed the door. The baby\'s cry haunts your sleep.',
      },
    ],
    autoEffect: null,
    realFactAr: 'في غزة 2024: الجيران يتشاركون آخر ما يملكون',
    realFactEn: 'In Gaza 2024: Neighbors share the last of what they have',
  },

  // ===== MONTH 10: Work Too Dangerous =====
  {
    id: 'work_dangerous',
    month: 10,
    recurring: false,
    autoEvent: false,
    titleAr: 'العمل أصبح خطراً على الحياة',
    titleEn: 'Work Becomes Life-Threatening',
    storyAr: 'مايو 2024. الوصول لمكان العمل أصبح مجازفة بالحياة.\nكل مهنة — طبيب، مهندس، تاجر — أصبحت هدفاً.\nالطريق إلى العمل يمر بمناطق القصف.',
    storyEn: 'May 2024. Getting to work has become a life gamble.\nEvery profession — doctor, engineer, merchant — has become a target.\nThe road to work passes through bombing zones.',
    choices: [
      {
        textAr: 'ترك العمل نهائياً (الراتب يصبح صفر)',
        textEn: 'Quit permanently (salary becomes zero)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 8,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'work_stop',
        messageAr: 'تركت العمل. آمن. لكن الراتب انتهى. المدخرات تنفد الآن.',
        messageEn: 'You quit work. Safe. But the salary ended. Savings are now depleting.',
      },
      {
        textAr: 'الاستمرار بالعمل (خطر الموت 5%/شهر)',
        textEn: 'Continue working (5% death risk/month)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        monthlyDeathHazard: 0.05,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'تستمر. تعرف الخطر. لكن الأسرة تحتاج الراتب.',
        messageEn: 'You continue. You know the risk. But the family needs the salary.',
      },
    ],
    autoEffect: null,
    realFactAr: 'غزة 2024: اغتيال أطباء ومهندسين وصحفيين في مناطق العمل',
    realFactEn: 'Gaza 2024: Doctors, engineers, and journalists targeted at work',
  },

  // ===== MONTH 11: Banking Crisis Escalation (Auto) =====
  {
    id: 'banking_crisis_2',
    month: 11,
    recurring: false,
    autoEvent: true,
    titleAr: 'تصاعد أزمة البنوك',
    titleEn: 'Banking Crisis Escalation',
    storyAr: 'يونيو 2024. ارتفعت رسوم سحب الراتب إلى 20%.\nبعض البنوك أغلقت نهائياً.\nالسيولة شبه منعدمة.',
    storyEn: 'June 2024. Salary withdrawal fees rose to 20%.\nSome banks closed permanently.\nLiquidity is nearly non-existent.',
    choices: [],
    autoEffect: { salaryPenaltyAdd: 0.20 },
    realFactAr: 'يونيو 2024: انهار النظام المصرفي في غزة بالكامل — رسوم تصل 30%',
    realFactEn: 'June 2024: Gaza banking system fully collapsed — fees reaching 30%',
  },

  // ===== MONTH 12: Third Displacement =====
  {
    id: 'displacement_3',
    month: 12,
    recurring: true,
    autoEvent: false,
    titleAr: 'النزوح الثالث — رفح',
    titleEn: 'Third Displacement — Rafah',
    storyAr: 'مايو 2024. أوامر إخلاء من رفح.\n1.4 مليون شخص في المواصي — المنطقة "الآمنة".\nالمواصي نفسها قُصفت لاحقاً.',
    storyEn: 'May 2024. Evacuation orders from Rafah.\n1.4 million in Al-Mawasi — the "safe" area.\nAl-Mawasi itself was later bombed.',
    choices: [
      {
        textAr: 'مشي إلى المواصي (مجاناً)',
        textEn: 'Walk to Al-Mawasi (free)',
        oneTimeCost: 0,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -20,
        deathRisk: 0.06,
        injuryRisk: 0,
        burdenId: 'shelter_mawasi',
        burdenLabelAr: 'خيمة المواصي',
        burdenLabelEn: 'Al-Mawasi tent',
        shelterSetupCost: 2000,
        consequence: null,
        messageAr: 'المواصي. رمال وبحر وخيام. ليست آمنة كما قالوا.',
        messageEn: 'Al-Mawasi. Sand and sea and tents. Not safe as they said.',
      },
      {
        textAr: 'شاحنة نقل ($1,500)',
        textEn: 'Hire a truck ($1,500)',
        oneTimeCost: 1500,
        monthlyCost: 1000,
        workHoursLost: 0,
        healthEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'shelter_truck_3',
        burdenLabelAr: 'خيمة المواصي',
        burdenLabelEn: 'Al-Mawasi tent',
        shelterSetupCost: 1000,
        consequence: null,
        messageAr: 'الشاحنة الثالثة. تعلمتم أن تحملوا فقط الضروري.',
        messageEn: 'The third truck. You learned to carry only the essentials.',
      },
      {
        textAr: 'البقاء في رفح (خطر اجتياح عسكري)',
        textEn: 'Stay in Rafah (military invasion risk)',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0.25,
        injuryRisk: 0.30,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: 'stay_dangerous',
        messageAr: 'بقيتم في رفح. الاجتياح يقترب. الأزقة تقتل.',
        messageEn: 'You stayed in Rafah. The invasion approaches. The alleys kill.',
      },
    ],
    autoEffect: null,
    realFactAr: 'مايو 2024: اجتاح الجيش الإسرائيلي رفح رغم وجود 1.4 مليون نازح',
    realFactEn: 'May 2024: Israeli army invaded Rafah despite 1.4 million displaced there',
  },

  // ===== MONTH 13: Baby Formula Price Rise (Auto) =====
  {
    id: 'formula_price_rise',
    month: 13,
    recurring: false,
    autoEvent: true,
    titleAr: 'ارتفاع سعر حليب الأطفال',
    titleEn: 'Baby Formula Price Rise',
    storyAr: 'يونيو 2024. الحليب الصناعي ارتفع إلى $300/شهر.\n(كان $200 الشهر الماضي)\nالتضخم لا يتوقف.',
    storyEn: 'June 2024. Baby formula rose to $300/month.\n(Was $200 last month)\nInflation does not stop.',
    choices: [],
    autoEffect: { updateBurdenId: 'baby_formula', newAmount: 300 },
    realFactAr: 'غزة 2024: أسعار حليب الأطفال ضاعفت كل شهر',
    realFactEn: 'Gaza 2024: Baby formula prices doubled each month',
    showOnlyIfChildren: true,
  },

  // ===== MONTH 14: Disease Outbreak (Auto) =====
  {
    id: 'disease_outbreak',
    month: 14,
    recurring: false,
    autoEvent: true,
    titleAr: 'تفشي الأمراض',
    titleEn: 'Disease Outbreak',
    storyAr: 'يوليو 2024. الأمراض تتفشى في مخيمات النازحين.\nالتهابات جلدية. التهاب كبد. حمى متكررة.\nالمستشفيات لا تعمل.',
    storyEn: 'July 2024. Diseases spreading in displacement camps.\nSkin infections. Hepatitis. Recurring fever.\nHospitals are not functioning.',
    choices: [],
    autoEffect: { healthEffect: -10, medicineCost: 500 },
    realFactAr: 'يوليو 2024: تفشي الكوليرا والتهاب الكبد والجرب في مخيمات غزة',
    realFactEn: 'July 2024: Cholera, hepatitis, and scabies outbreaks in Gaza camps',
  },

  // ===== MONTH 15: Polio Returns =====
  {
    id: 'polio_returns',
    month: 15,
    recurring: false,
    autoEvent: false,
    titleAr: 'عودة شلل الأطفال',
    titleEn: 'Polio Returns',
    storyAr: 'أغسطس 2024. اكتُشفت حالات شلل أطفال في غزة.\nآخر مرة ظهر فيها منذ 25 عاماً.\nالأطفال في خطر.',
    storyEn: 'August 2024. Polio cases discovered in Gaza.\nLast appeared 25 years ago.\nChildren are at risk.',
    choices: [
      {
        textAr: 'حملة تطعيم طارئة ($300)',
        textEn: 'Emergency vaccination campaign ($300)',
        oneTimeCost: 300,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'لقّحتم الأطفال. الأمل أن اللقاح يصل في الوقت.',
        messageEn: 'You vaccinated the children. Hope the vaccine arrives in time.',
      },
      {
        textAr: 'لا يمكن الوصول للتطعيم',
        textEn: 'Cannot access vaccination',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -15,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        childrenOnly: true,
        consequence: null,
        messageAr: 'لا لقاح. تصلّي ألا يُصاب الأطفال.',
        messageEn: 'No vaccine. You pray the children don\'t get sick.',
      },
    ],
    autoEffect: null,
    realFactAr: 'أغسطس 2024: اكتشاف شلل الأطفال في غزة لأول مرة منذ ربع قرن',
    realFactEn: 'August 2024: Polio discovered in Gaza for the first time in a quarter century',
  },

  // ===== MONTH 16: Al-Mawasi Bombed (Auto) =====
  {
    id: 'mawasi_bombed',
    month: 16,
    recurring: false,
    autoEvent: true,
    titleAr: 'قصف المواصي "المنطقة الآمنة"',
    titleEn: 'Al-Mawasi "Safe Zone" Bombed',
    storyAr: 'سبتمبر 2024. قُصفت المواصي التي أُعلن أنها آمنة.\nلا يوجد مكان آمن في غزة.\nالقصف وسط الخيام.',
    storyEn: 'September 2024. Al-Mawasi declared safe zone was bombed.\nThere is no safe place in Gaza.\nBombing amidst the tents.',
    choices: [],
    autoEffect: { deathRisk: 0.20, injuryRisk: 0.15 },
    realFactAr: 'سبتمبر 2024: قُصفت مناطق إيواء النازحين في المواصي بغارات مباشرة',
    realFactEn: 'September 2024: Displacement shelters in Al-Mawasi struck in direct airstrikes',
  },

  // ===== MONTH 17: Starvation Deepens =====
  {
    id: 'starvation_deepens',
    month: 17,
    recurring: false,
    autoEvent: false,
    titleAr: 'تعمق المجاعة',
    titleEn: 'Starvation Deepens',
    storyAr: 'أكتوبر 2024. المجاعة تتفاقم.\nالعائلات تأكل مرة واحدة في اليوم أو أقل.\nالأطفال يفقدون الوزن بسرعة مرعبة.',
    storyEn: 'October 2024. Famine is worsening.\nFamilies eat once a day or less.\nChildren are losing weight at a terrifying speed.',
    choices: [
      {
        textAr: 'زيادة ميزانية الطعام ($200 إضافية/شهر)',
        textEn: 'Increase food budget ($200 more/month)',
        oneTimeCost: 0,
        monthlyCost: 200,
        workHoursLost: 0,
        healthEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'extra_food',
        burdenLabelAr: 'طعام إضافي',
        burdenLabelEn: 'Extra food',
        consequence: null,
        messageAr: 'تزيدون الإنفاق على الطعام. المدخرات تتراجع. الأجسام تتحسن.',
        messageEn: 'You increase food spending. Savings drop. Bodies improve.',
      },
      {
        textAr: 'الصبر على الوضع الحالي',
        textEn: 'Endure the current situation',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -15,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'تصبرون. الأجسام تضعف. لكن المال محدود.',
        messageEn: 'You endure. Bodies weaken. But money is limited.',
      },
    ],
    autoEffect: null,
    realFactAr: 'أكتوبر 2024: IPC تصنف شمال غزة مجاعة رسمية — أول مجاعة مصطنعة منذ عقود',
    realFactEn: 'October 2024: IPC classifies northern Gaza as official famine — first engineered famine in decades',
  },

  // ===== MONTH 18: Work Hazard Intensifies =====
  {
    id: 'work_hazard_2',
    month: 18,
    recurring: false,
    autoEvent: true,
    titleAr: 'تصاعد خطر العمل',
    titleEn: 'Work Hazard Intensifies',
    storyAr: 'نوفمبر 2024. خطر الاستهداف في العمل يتصاعد.\nكل من يتنقل في الشوارع معرض للقنص أو القصف.',
    storyEn: 'November 2024. Risk of being targeted at work escalates.\nAnyone moving in the streets risks sniping or bombing.',
    choices: [],
    autoEffect: { workingDeathRiskIncrease: 0.08 },
    realFactAr: 'نوفمبر 2024: استمرار استهداف العاملين في القطاعات الطبية والصحفيين',
    realFactEn: 'November 2024: Continued targeting of healthcare workers and journalists',
  },

  // ===== MONTH 19: North Gaza Siege =====
  {
    id: 'north_siege',
    month: 19,
    recurring: false,
    autoEvent: true,
    titleAr: 'حصار شمال غزة',
    titleEn: 'North Gaza Siege',
    storyAr: 'ديسمبر 2024. حصار كامل على شمال غزة.\nلا طعام ولا ماء يدخل. جيدال الحصار.',
    storyEn: 'December 2024. Complete siege on northern Gaza.\nNo food or water enters. Total siege.',
    choices: [],
    autoEffect: { northGazaFoodCostIncrease: 300, healthEffect: -10 },
    realFactAr: 'ديسمبر 2024: حصار خانق تام على شمال غزة — تقارير مجاعة حادة',
    realFactEn: 'December 2024: Total siege on northern Gaza — reports of acute famine',
  },

  // ===== MONTH 20: Aid Blocked =====
  {
    id: 'aid_blocked',
    month: 20,
    recurring: false,
    autoEvent: true,
    titleAr: 'إغلاق كامل أمام المساعدات',
    titleEn: 'Aid Completely Blocked',
    storyAr: 'يناير 2025. المساعدات توقفت شبه كليا.\nالأسعار ترتفع 50% إضافية.\nالموت من الجوع يتسارع.',
    storyEn: 'January 2025. Aid has almost completely stopped.\nPrices rise 50% more.\nDeath from starvation accelerates.',
    choices: [],
    autoEffect: { allBurdenIncrease: 0.50 },
    realFactAr: 'يناير 2025: وصول المساعدات إلى أدنى مستوى — أقل من 60 شاحنة/يوم مقابل 500 قبل الحرب',
    realFactEn: 'January 2025: Aid access at lowest point — under 60 trucks/day vs 500 pre-war',
  },

  // ===== MONTH 21: Currency Collapse =====
  {
    id: 'currency_collapse',
    month: 21,
    recurring: false,
    autoEvent: true,
    titleAr: 'انهيار قيمة المال',
    titleEn: 'Currency Collapse',
    storyAr: 'فبراير 2025. التضخم دمّر قيمة مدخراتك.\nكل $100 أصبحت تساوي $80 فعلياً.\nمدخراتك تتآكل بلا توقف.',
    storyEn: 'February 2025. Inflation destroyed the value of your savings.\nEvery $100 is now worth $80 effectively.\nYour savings erode without stopping.',
    choices: [],
    autoEffect: { savingsDevaluation: 0.20 },
    realFactAr: 'فبراير 2025: التضخم في غزة يتجاوز 500% — انهيار الشيكل في المناطق الخاضعة لسيطرة حماس',
    realFactEn: 'February 2025: Gaza inflation exceeds 500% — shekel collapse in Hamas-controlled areas',
  },

  // ===== MONTH 22: School Bombing =====
  {
    id: 'school_bombing',
    month: 22,
    recurring: false,
    autoEvent: true,
    titleAr: 'قصف مدرسة تؤوي النازحين',
    titleEn: 'School Sheltering Displaced Bombed',
    storyAr: 'مارس 2025. المدرسة التي تؤوي عائلات بالقرب منكم قُصفت.\nالأطفال الذين رأيتموهم يلعبون أمس...',
    storyEn: 'March 2025. The school sheltering families near you was bombed.\nThe children you saw playing yesterday...',
    choices: [],
    autoEffect: { childrenHealthEffect: -20, deathRisk: 0.10 },
    realFactAr: 'مارس 2025: قصف مدارس تعمل كمراكز إيواء — عشرات الشهداء',
    realFactEn: 'March 2025: Schools operating as shelters bombed — dozens of martyrs',
  },

  // ===== MONTH 23: Hospital Destroyed =====
  {
    id: 'hospital_destroyed',
    month: 23,
    recurring: false,
    autoEvent: true,
    titleAr: 'تدمير آخر المستشفيات',
    titleEn: 'Last Hospitals Destroyed',
    storyAr: 'أبريل 2025. آخر مستشفى قريب خرج عن الخدمة.\nأسعار الدواء ارتفعت 200%.\nلا علاج لأي مرض.',
    storyEn: 'April 2025. The last nearby hospital went out of service.\nMedicine prices rose 200%.\nNo treatment for any disease.',
    choices: [],
    autoEffect: { medicineCostMultiplier: 3.0, healthEffect: -5 },
    realFactAr: 'أبريل 2025: تدمير أو إخراج عن الخدمة لـ 90% من المستشفيات الغزاوية',
    realFactEn: 'April 2025: 90% of Gaza hospitals destroyed or out of service',
  },

  // ===== MONTH 24: WFP Aid Resumes =====
  {
    id: 'wfp_aid_resumes',
    month: 24,
    recurring: false,
    autoEvent: true,
    titleAr: 'استئناف جزئي لمساعدات WFP',
    titleEn: 'Partial WFP Aid Resumes',
    storyAr: 'مايو 2025. برنامج الأغذية العالمي يُعلن استئناف جزئي.\nتوزيع محدود. $500 قيمة مؤن للأسرة.',
    storyEn: 'May 2025. World Food Programme announces partial resumption.\nLimited distribution. $500 worth of supplies per family.',
    choices: [],
    autoEffect: { savingsBonus: 500 },
    realFactAr: 'مايو 2025: WFP يعلن استئناف محدود جداً — أقل من 10% من الاحتياج الفعلي',
    realFactEn: 'May 2025: WFP announces very limited resumption — less than 10% of actual need',
  },

  // ===== MONTH 25: Fourth Displacement =====
  {
    id: 'displacement_4',
    month: 25,
    recurring: false,
    autoEvent: false,
    titleAr: 'النزوح الرابع',
    titleEn: 'Fourth Displacement',
    storyAr: 'يونيو 2025. أوامر إخلاء من المنطقة الحالية.\nالمرة الرابعة. لا مكان آمن.\nتعلمتم أن تأخذوا فقط ما تستطيعون حمله.',
    storyEn: 'June 2025. Evacuation orders from current area.\nThe fourth time. No safe place.\nYou have learned to take only what you can carry.',
    choices: [
      {
        textAr: 'المشي مجدداً (مجاناً)',
        textEn: 'Walk again (free)',
        oneTimeCost: 0,
        monthlyCost: 800,
        workHoursLost: 0,
        healthEffect: -15,
        deathRisk: 0.05,
        injuryRisk: 0,
        burdenId: 'shelter_4',
        burdenLabelAr: 'مأوى رابع',
        burdenLabelEn: 'Fourth shelter',
        shelterSetupCost: 1500,
        consequence: null,
        messageAr: 'المشي الرابع. الأرجل ترفض. لكن لا خيار.',
        messageEn: 'The fourth walk. Legs refuse. But no choice.',
      },
      {
        textAr: 'شاحنة ($1,000)',
        textEn: 'Truck ($1,000)',
        oneTimeCost: 1000,
        monthlyCost: 800,
        workHoursLost: 0,
        healthEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: 'shelter_truck_4',
        burdenLabelAr: 'مأوى رابع',
        burdenLabelEn: 'Fourth shelter',
        shelterSetupCost: 800,
        consequence: null,
        messageAr: 'الشاحنة الرابعة. الأطفال صامتون. تعلّموا أن لا يبكوا.',
        messageEn: 'The fourth truck. The children are silent. They learned not to cry.',
      },
    ],
    autoEffect: null,
    realFactAr: 'يونيو 2025: معظم الغزيين نُزحوا 4 مرات أو أكثر',
    realFactEn: 'June 2025: Most Gazans displaced 4 times or more',
  },

  // ===== MONTH 26: Ceasefire Rumor =====
  {
    id: 'ceasefire_rumor',
    month: 26,
    recurring: false,
    autoEvent: true,
    titleAr: 'إشاعة وقف إطلاق النار... ثم الخيبة',
    titleEn: 'Ceasefire Rumor... Then Disappointment',
    storyAr: 'يوليو 2025. شائعات عن وقف إطلاق نار وشيك.\nفرح قصير. ثم القصف عاد أشد مما كان.\nالأمل يُقتل مرتين.',
    storyEn: 'July 2025. Rumors of imminent ceasefire.\nBrief joy. Then bombing returned fiercer than before.\nHope is killed twice.',
    choices: [],
    autoEffect: { moraleBonusThenPenalty: { bonus: 10, penalty: -20 } },
    realFactAr: 'يوليو 2025: مفاوضات وقف إطلاق النار تنهار مراراً — السكان يعيشون في دوامة الأمل والإحباط',
    realFactEn: 'July 2025: Ceasefire negotiations collapse repeatedly — population lives in cycle of hope and despair',
  },

  // ===== MONTH 27: Aid Workers Killed =====
  {
    id: 'aid_workers_killed',
    month: 27,
    recurring: false,
    autoEvent: true,
    titleAr: 'اغتيال عمال الإغاثة (حادثة WCK)',
    titleEn: 'Aid Workers Killed (WCK Incident)',
    storyAr: 'أغسطس 2025. استُهدفت سيارات إغاثة World Central Kitchen.\nقُتل 7 عمال إغاثة دوليين.\nالمنظمات الدولية علّقت عملياتها.',
    storyEn: 'August 2025. World Central Kitchen aid vehicles targeted.\n7 international aid workers killed.\nInternational organizations suspended operations.',
    choices: [],
    autoEffect: { foodCostIncrease: 150, durationMonths: 2 },
    realFactAr: '1 أبريل 2024: مقتل 7 من موظفي WCK — علّقت عشرات المنظمات عملياتها مؤقتاً',
    realFactEn: 'April 1, 2024: 7 WCK staff killed — dozens of organizations temporarily suspended operations',
  },

  // ===== MONTH 28: Tent Camp Bombed =====
  {
    id: 'tent_camp_bombed',
    month: 28,
    recurring: false,
    autoEvent: true,
    titleAr: 'قصف مخيم الخيام',
    titleEn: 'Tent Camp Bombed',
    storyAr: 'سبتمبر 2025. قُصف المخيم الذي تسكنه.\nخيام تحترق. صراخ الجيران.\nلا مكان تذهب إليه.',
    storyEn: 'September 2025. The camp you live in was bombed.\nTents burning. Neighbors screaming.\nNowhere to go.',
    choices: [],
    autoEffect: { deathRisk: 0.15, injuryRisk: 0.20 },
    realFactAr: 'سبتمبر 2025: قصف متواصل لمخيمات النازحين في رفح والمواصي',
    realFactEn: 'September 2025: Continued bombing of displacement camps in Rafah and Al-Mawasi',
  },

  // ===== MONTH 29: Malnutrition Crisis =====
  {
    id: 'malnutrition_crisis',
    month: 29,
    recurring: false,
    autoEvent: true,
    titleAr: 'أزمة سوء التغذية الحادة',
    titleEn: 'Acute Malnutrition Crisis',
    storyAr: 'أكتوبر 2025. سوء التغذية الحاد يضرب الجميع.\nالجسم لا يتحمل أكثر. الأطفال الأشد تضرراً.',
    storyEn: 'October 2025. Acute malnutrition strikes everyone.\nThe body can take no more. Children are the most affected.',
    choices: [],
    autoEffect: { healthEffect: -20 },
    realFactAr: 'أكتوبر 2025: 96% من أطفال غزة دون سن الخامسة يعانون سوء تغذية حاداً',
    realFactEn: 'October 2025: 96% of Gaza children under 5 suffer acute malnutrition',
  },

  // ===== MONTH 30: Winter Without Shelter =====
  {
    id: 'winter_no_shelter',
    month: 30,
    recurring: false,
    autoEvent: true,
    titleAr: 'الشتاء بلا مأوى حقيقي',
    titleEn: 'Winter Without Real Shelter',
    storyAr: 'نوفمبر 2025. الشتاء يضرب. الخيام لا تكفي.\nالمطر يدخل. الأطفال يرتجفون.\nالبرد قاتل كالقصف.',
    storyEn: 'November 2025. Winter strikes. Tents are not enough.\nRain seeps in. Children shiver.\nCold kills like bombs.',
    choices: [],
    autoEffect: { healthEffect: -15 },
    realFactAr: 'نوفمبر 2025: فيضانات وبرد قارس في مخيمات غزة — موجة نزلات برد وأمراض',
    realFactEn: 'November 2025: Floods and extreme cold in Gaza camps — wave of colds and disease',
  },

  // ===== MONTH 31: Ceasefire Negotiations =====
  {
    id: 'ceasefire_negotiations',
    month: 31,
    recurring: false,
    autoEvent: false,
    titleAr: 'مفاوضات وقف إطلاق النار',
    titleEn: 'Ceasefire Negotiations',
    storyAr: 'ديسمبر 2025. مفاوضات جدية تجري في الدوحة والقاهرة.\nهل تحاول العودة لمنزلك استعداداً؟\nأم تنتظر تأكيداً أولاً؟',
    storyEn: 'December 2025. Serious negotiations in Doha and Cairo.\nDo you try to return home in preparation?\nOr wait for confirmation first?',
    choices: [
      {
        textAr: 'محاولة العودة مبكراً',
        textEn: 'Attempt early return',
        oneTimeCost: 500,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -5,
        deathRisk: 0.08,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'حاولتم العودة. الطرق محفوفة بالألغام. خطر حقيقي.',
        messageEn: 'You attempted return. Roads are mined. Real danger.',
      },
      {
        textAr: 'الانتظار في مكانكم',
        textEn: 'Wait in place',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'تنتظرون. الانتظار أصعب من الحرب.',
        messageEn: 'You wait. Waiting is harder than war.',
      },
    ],
    autoEffect: null,
    realFactAr: 'ديسمبر 2025: مفاوضات مكوكية مستمرة بين حماس وإسرائيل بوساطة قطرية',
    realFactEn: 'December 2025: Shuttle negotiations ongoing between Hamas and Israel with Qatari mediation',
  },

  // ===== MONTH 32: Partial Ceasefire =====
  {
    id: 'partial_ceasefire',
    month: 32,
    recurring: false,
    autoEvent: true,
    titleAr: 'هدنة جزئية — تخفيف الأعباء',
    titleEn: 'Partial Ceasefire — Cost Relief',
    storyAr: 'يناير 2026. اتفاق هدنة جزئي.\nالقصف تراجع. بعض الممرات فُتحت.\nالأسعار بدأت تنخفض قليلاً.',
    storyEn: 'January 2026. Partial ceasefire agreement.\nBombing decreased. Some corridors opened.\nPrices started to drop slightly.',
    choices: [],
    autoEffect: { allBurdenDecrease: 0.20 },
    realFactAr: 'يناير 2026: بدء تطبيق هدنة جزئية — سماح بدخول مزيد من المساعدات',
    realFactEn: 'January 2026: Partial ceasefire begins — allowing more aid entry',
  },

  // ===== MONTH 33: Return Attempt Blocked =====
  {
    id: 'return_blocked',
    month: 33,
    recurring: false,
    autoEvent: false,
    titleAr: 'محاولة العودة... محاصرة',
    titleEn: 'Return Attempt... Blocked',
    storyAr: 'فبراير 2026. تحاول العودة لمنزلك.\nالطرق مقطوعة. المدينة لا تشبه ما تذكر.\nكل ما بناه أبوك... ركام.',
    storyEn: 'February 2026. You try to return home.\nRoads are cut. The city does not look like you remember.\nEverything your father built... rubble.',
    choices: [
      {
        textAr: 'المضي في محاولة العودة',
        textEn: 'Continue return attempt',
        oneTimeCost: 300,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: -5,
        moraleEffect: -15,
        deathRisk: 0.05,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'وصلتم... لكن البيت لا يوجد. الحي رماد.',
        messageEn: 'You arrived... but the house is gone. The neighborhood is ash.',
      },
      {
        textAr: 'الانتظار حتى تُفتح الطرق رسمياً',
        textEn: 'Wait for roads to officially open',
        oneTimeCost: 0,
        monthlyCost: 0,
        workHoursLost: 0,
        healthEffect: 0,
        deathRisk: 0,
        injuryRisk: 0,
        burdenId: null,
        burdenLabelAr: '',
        burdenLabelEn: '',
        consequence: null,
        messageAr: 'تنتظرون. الوقت ثقيل. لكن أسلم.',
        messageEn: 'You wait. Time is heavy. But safer.',
      },
    ],
    autoEffect: null,
    realFactAr: 'فبراير 2026: النازحون يعودون لأحياء مدمرة بالكامل — لا ماء ولا كهرباء ولا مبانٍ',
    realFactEn: 'February 2026: Displaced return to completely destroyed neighborhoods — no water, electricity, or buildings',
  },

  // ===== MONTH 34: Ceasefire Holds =====
  {
    id: 'ceasefire_holds',
    month: 34,
    recurring: false,
    autoEvent: true,
    titleAr: 'وقف إطلاق النار يصمد — يناير 2026',
    titleEn: 'Ceasefire Holds — January 2026',
    storyAr: 'يناير 2026. وقف إطلاق النار يبدو حقيقياً هذه المرة.\nالطائرات توقفت. الشوارع... صامتة.\nالراتب بدأ يعود جزئياً.',
    storyEn: 'January 2026. The ceasefire seems real this time.\nThe planes stopped. The streets... silent.\nSalary has started to partially return.',
    choices: [],
    autoEffect: { salaryRestore: 0.50, allBurdenDecrease: 0.30 },
    realFactAr: '19 يناير 2025: دخول وقف إطلاق النار حيز التنفيذ — أول صمت حقيقي بعد 15 شهراً',
    realFactEn: 'January 19, 2025: Ceasefire enters into effect — first real silence after 15 months',
  },

  // ===== MONTH 35: Return to Rubble =====
  {
    id: 'return_to_rubble',
    month: 35,
    recurring: false,
    autoEvent: true,
    titleAr: 'العودة إلى الركام',
    titleEn: 'Return to Rubble',
    storyAr: 'مارس 2026. عدتم أخيراً.\nلكن البيت لا يوجد. الحي لا يوجد.\n60% من المباني دُمرت أو تضررت.\nعدتم لكن لم يبق ما تعودوا إليه.',
    storyEn: 'March 2026. You finally returned.\nBut the house is gone. The neighborhood is gone.\n60% of buildings destroyed or damaged.\nYou returned but there is nothing left to return to.',
    choices: [],
    autoEffect: { homeValueLoss: true, moraleEffect: -30 },
    realFactAr: 'مارس 2026: 60% من مباني غزة مدمرة أو متضررة — التكلفة تُقدر بـ $40-60 مليار لإعادة الإعمار',
    realFactEn: 'March 2026: 60% of Gaza buildings destroyed or damaged — $40-60 billion estimated for reconstruction',
  },

  // ===== MONTH 36: Final Month =====
  {
    id: 'final_count',
    month: 36,
    recurring: false,
    autoEvent: true,
    titleAr: 'النهاية — الإحصاء الأخير',
    titleEn: 'The End — Final Count',
    storyAr: 'أبريل 2026.\n27 شهراً من الحرب.\nمن نجا من عائلتك؟\nماذا بقي من حياتكم؟',
    storyEn: 'April 2026.\n27 months of war.\nWho survived from your family?\nWhat is left of your lives?',
    choices: [],
    autoEffect: { triggerEndGame: true },
    realFactAr: 'غزة 2026: أكثر من 55,000 شهيد. مليون وثمانمائة ألف نازح. مجاعة متواصلة.',
    realFactEn: 'Gaza 2026: Over 55,000 martyred. 1.8 million displaced. Ongoing famine.',
  },
];
