// monthly_challenges.js - 36-month emotional story moments for Gaza war simulation
// Oct 2023 (month 1) through Jan 2026 (month 36)
// Each challenge is a human moment — no prices shown to the player.

const MONTHLY_CHALLENGES = [

  // ===== MONTH 1 =====
  {
    id: 'bab_al_bayt',
    month: 1,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'وطن',
    titleAr: 'باب البيت',
    titleEn: 'The Door of Home',
    storyAr: `دقيقة واحدة قبل أن تغلق الباب للمرة الأخيرة.\nالجيران يركضون. الشارع يصرخ.\nأنت تقف أمام بيتك وتنظر للداخل مرة واحدة.\nماذا تأخذ؟`,
    storyEn: `One minute before you close the door for the last time.\nNeighbors run. The street screams.\nYou stand in front of your home and look inside one last time.\nWhat do you take?`,
    choices: [
      {
        textAr: 'تأخذ مفتاح البيت',
        textEn: 'You take the house key',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'المفتاح في يدك. ثقيل مثل الوعد. هذا يعني أنك ستعود.',
        messageEn: 'The key is in your hand. Heavy like a promise. This means you will return.',
      },
      {
        textAr: 'تأخذ صورة العائلة',
        textEn: 'You take the family photo',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الصورة في صدرك. وجوههم محفورة في قلبك. لن تضيع طالما أنت تتذكر.',
        messageEn: 'The photo against your chest. Their faces carved in your heart. They won\'t be lost as long as you remember.',
      },
      {
        textAr: 'لا تأخذ شيئاً — تغلق الباب وتمشي',
        textEn: 'You take nothing — close the door and walk',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: -8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'تمشي بلا شيء. الثقل كله في صدرك. البيت خلفك. الطريق أمامك مجهول.',
        messageEn: 'You walk with nothing. All the weight is in your chest. Home behind you. The road ahead unknown.',
      },
    ],
    realFactAr: 'أكتوبر 2023: أُمر 1.1 مليون شخص بمغادرة بيوتهم خلال 24 ساعة.',
    realFactEn: 'October 2023: 1.1 million people ordered to leave their homes within 24 hours.',
  },

  // ===== MONTH 2 =====
  {
    id: 'taboor_al_maa',
    month: 2,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'صمود',
    titleAr: 'طابور الماء',
    titleEn: 'The Water Queue',
    storyAr: `ثلاث ساعات في الطابور.\nالشمس فوقك. الأرض ساخنة تحتك.\nأمامك عجوز تحمل جركن فارغاً.\nخلفك طفل يبكي بصمت.\nأنت في المنتصف. صامد.`,
    storyEn: `Three hours in the queue.\nThe sun above you. The hot ground beneath.\nIn front of you an old woman carrying an empty jerrycan.\nBehind you a child crying silently.\nYou are in the middle. Holding on.`,
    choices: [
      {
        textAr: 'تتنازل عن دورك للعجوز',
        textEn: 'You give your turn to the old woman',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: 12,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'نظرت إليك بعيون دامعة ولم تقل شيئاً. بعض الأشياء أكبر من الكلام.',
        messageEn: 'She looked at you with wet eyes and said nothing. Some things are bigger than words.',
      },
      {
        textAr: 'تبقى في دورك — العائلة تنتظر',
        textEn: 'You keep your place — the family is waiting',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: -3,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'ثلاث ساعات. وصلت. الماء في يدك. وشيء آخر في قلبك لن يرحل بسهولة.',
        messageEn: 'Three hours. You made it. Water in your hands. Something else in your heart that won\'t leave easily.',
      },
    ],
    realFactAr: 'نوفمبر 2023: انخفض إمداد المياه 94% — كل شخص يحصل على أقل من لتر يومياً.',
    realFactEn: 'November 2023: Water supply fell 94% — each person received less than one liter per day.',
  },

  // ===== MONTH 3 =====
  {
    id: 'mata_narjaa',
    month: 3,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'وطن',
    titleAr: 'متى نرجع؟',
    titleEn: 'When Do We Go Back?',
    storyAr: `الليل.\nالطفل ينظر إليك بعيون كبيرة لا تعرف الكذب.\n"بابا... متى نرجع للبيت؟"\nأنت تعرف الإجابة. لكنك لا تستطيع نطقها.`,
    storyEn: `Night.\nThe child looks at you with wide eyes that don\'t know how to lie.\n"Baba... when do we go back home?"\nYou know the answer. But you cannot say it.`,
    choices: [
      {
        textAr: '"قريباً يا حبيبي. قريباً."',
        textEn: '"Soon, my love. Soon."',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'أغمض عينيه وآمن بك. الكذبة الأولى التي تحتاجها الحرب.',
        messageEn: 'He closed his eyes and believed you. The first lie that war demands.',
      },
      {
        textAr: '"لا أعرف. لكن أنا معك."',
        textEn: '"I don\'t know. But I am with you."',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'صمت لحظة. ثم وضع رأسه على صدرك. الصدق أحياناً يشفي.',
        messageEn: 'A moment of silence. Then he laid his head on your chest. Honesty sometimes heals.',
      },
      {
        textAr: 'لا تجيب. تضمه فقط.',
        textEn: 'You don\'t answer. You just hold him.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: 3,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الصمت احتضان. أحياناً الجسد يقول ما يعجز عنه اللسان.',
        messageEn: 'Silence is an embrace. Sometimes the body says what the tongue cannot.',
      },
    ],
    showOnlyIfChildren: true,
    realFactAr: 'ديسمبر 2023: أكثر من مليون طفل نُزّحوا قسراً من بيوتهم في غزة.',
    realFactEn: 'December 2023: Over one million children were forcibly displaced from their homes in Gaza.',
  },

  // ===== MONTH 4 =====
  {
    id: 'qahwat_al_sabah',
    month: 4,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'صمود',
    titleAr: 'قهوة الصباح',
    titleEn: 'Morning Coffee',
    storyAr: `وجدت ملعقة قهوة في قاع الحقيبة.\nحجر صغير من نار. قِدر قديم على حجرين.\nالرائحة انتشرت في الخيمة.\nالجيران توقفوا ونظروا.\nهذا فعل مقاومة صغير.`,
    storyEn: `You found a spoonful of coffee at the bottom of the bag.\nA small stone for fire. An old pot on two rocks.\nThe smell spread through the tent.\nNeighbors stopped and looked.\nThis is a small act of resistance.`,
    choices: [
      {
        textAr: 'تصنع القهوة وتوزعها على الجيران',
        textEn: 'You make the coffee and share it with neighbors',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 15,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'جلسوا معك. لم يتكلموا كثيراً. لكن الدفء كان حاضراً. هذا يكفي.',
        messageEn: 'They sat with you. Didn\'t say much. But warmth was present. That is enough.',
      },
      {
        textAr: 'تصنعها لنفسك فقط — لحظة هدوء نادرة',
        textEn: 'You make it just for yourself — a rare moment of quiet',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'دقيقتان. الفنجان بين يديك. العالم صامت للحظة. ثم يعود الصوت.',
        messageEn: 'Two minutes. The cup between your hands. The world silent for a moment. Then sound returns.',
      },
    ],
    realFactAr: 'يناير 2024: أسعار القهوة في غزة ارتفعت أكثر من 800% — ومع ذلك ظل الناس يصنعونها.',
    realFactEn: 'January 2024: Coffee prices in Gaza rose over 800% — yet people still found ways to make it.',
  },

  // ===== MONTH 5 =====
  {
    id: 'dahka_mudhniba',
    month: 5,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'نفس',
    titleAr: 'ضحكة مذنبة',
    titleEn: 'A Guilty Laugh',
    storyAr: `طفلك سقط وهو يمشي. بطريقة مضحكة.\nنظر إليك. ابتسم.\nشيء في صدرك أراد الضحك.\nلكن في مكان ما يحترق كل شيء.\nهل يحق لك أن تضحك؟`,
    storyEn: `Your child tripped while walking. In a funny way.\nHe looked at you. Smiled.\nSomething in your chest wanted to laugh.\nBut somewhere everything is burning.\nDo you have the right to laugh?`,
    choices: [
      {
        textAr: 'تضحك معه. من القلب.',
        textEn: 'You laugh with him. From the heart.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: 15,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الضحك ليس خيانة. الضحك دليل أن فيك شيئاً لم يمت بعد.',
        messageEn: 'Laughing is not betrayal. Laughing is proof that something in you has not died yet.',
      },
      {
        textAr: 'تبتسم فقط — القلب لا يستطيع أكثر',
        textEn: 'You only smile — the heart cannot do more',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'ابتسامة نصف قلب. لكنه رآها وكفى. بعض الأحيان النصف يملأ الكل.',
        messageEn: 'A half-hearted smile. But he saw it and it was enough. Sometimes half fills everything.',
      },
      {
        textAr: 'لا تستطيع. تحول وجهك.',
        textEn: 'You can\'t. You turn away.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: -10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'رأى ظهرك فابتلع ضحكته. أنت لم تقصد. الحرب تفعل هذا.',
        messageEn: 'He saw your back and swallowed his laugh. You didn\'t mean it. War does this.',
      },
    ],
    showOnlyIfChildren: true,
    realFactAr: 'دراسات نفسية: الضحك في أوقات الحرب ظاهرة إنسانية طبيعية — وليست خيانة.',
    realFactEn: 'Psychological studies: Laughter during wartime is a natural human phenomenon — not betrayal.',
  },

  // ===== MONTH 6 =====
  {
    id: 'al_jar_yaarid_taam',
    month: 6,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'وطن',
    titleAr: 'الجار يعرض طعاماً',
    titleEn: 'The Neighbor Offers Food',
    storyAr: `أبو سامر طرق خيمتك.\nفي يده كيس فيه خبز وبعض الزيتون.\n"أسرتنا طبخت اليوم. خذ هذا."\nعيناه تعرفان أنك لم تأكل منذ يومين.\nوأنت تعرف أن هذا آخر ما عنده.`,
    storyEn: `Abu Samer knocked on your tent.\nIn his hand a bag with bread and some olives.\n"Our family cooked today. Take this."\nHis eyes know you haven\'t eaten in two days.\nAnd you know this is the last of what he has.`,
    choices: [
      {
        textAr: 'تقبل. وتشكره بصمت.',
        textEn: 'You accept. And thank him in silence.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 10,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'أكلتم. الخبز كان دافئاً. الكرم الحقيقي هو أن تقبل كما تعطي.',
        messageEn: 'You ate. The bread was warm. True generosity is accepting as you give.',
      },
      {
        textAr: 'ترفض — لا تريد أن تأخذ من فمه',
        textEn: 'You refuse — you won\'t take from his mouth',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -8,
        moraleEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'ذهب. تركك بكبريائك وبطنك الفارغة. الكرامة تُشبع أحياناً. وأحياناً لا تكفي.',
        messageEn: 'He left. Left you with your pride and empty stomach. Dignity feeds sometimes. And sometimes it\'s not enough.',
      },
      {
        textAr: 'تقبل نصفه وتعيد إليه النصف الآخر',
        textEn: 'You accept half and return the other half to him',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: 15,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'ضحك بصوت خافت. "أنتم وأنا سواء." هذا هو المعنى الحقيقي لكلمة جار.',
        messageEn: 'He laughed softly. "You and I are the same." This is the true meaning of the word neighbor.',
      },
    ],
    realFactAr: 'التقارير الميدانية: الأسر في غزة تتشارك الطعام مع بعضها حتى في أشد لحظات الشح.',
    realFactEn: 'Field reports: Families in Gaza share food with each other even in the most severe moments of scarcity.',
  },

  // ===== MONTH 7 =====
  {
    id: 'al_kadhba_al_rahima',
    month: 7,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'نفس',
    titleAr: 'الكذبة الرحيمة',
    titleEn: 'The Merciful Lie',
    storyAr: `طفلك يمسك بيدك في الظلام.\n"ليش ما في ضو؟"\nأنت تعرف الجواب الحقيقي.\nلكن عيناه لا تحتملانه الآن.`,
    storyEn: `Your child holds your hand in the dark.\n"Why is there no light?"\nYou know the real answer.\nBut his eyes cannot hold it right now.`,
    choices: [
      {
        textAr: '"الكهرباء ناعسة. بكرة تصحى."',
        textEn: '"The electricity is sleeping. It will wake tomorrow."',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'ضحك وأغمض عينيه. الكذب أحياناً هو أقسى أشكال الحب.',
        messageEn: 'He laughed and closed his eyes. Lying is sometimes the harshest form of love.',
      },
      {
        textAr: '"الكهرباء راحت. لكن إحنا مع بعض."',
        textEn: '"The electricity is gone. But we are together."',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'فكّر قليلاً. "ومع بعض أحسن." قالها بصوت نعسان وغفا.',
        messageEn: 'He thought a little. "And together is better." He said it in a sleepy voice and dozed off.',
      },
    ],
    showOnlyIfChildren: true,
    realFactAr: 'غزة 2023: قُطعت الكهرباء كلياً — السكان يعيشون في ظلام دامس لأشهر.',
    realFactEn: 'Gaza 2023: Electricity was cut completely — residents living in complete darkness for months.',
  },

  // ===== MONTH 8 =====
  {
    id: 'al_qasf',
    month: 8,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'قصف',
    titleAr: 'القصف',
    titleEn: 'The Strike',
    storyAr: `الصوت قبل أن يكون له معنى.\nجسدك تحرّك قبل أن تفكر.\nالجدار يرتجف. الأرض تهتز.\nطفلك كان في الزاوية الأخرى.`,
    storyEn: `The sound before it has meaning.\nYour body moved before you thought.\nThe wall trembles. The ground shakes.\nYour child was in the other corner.`,
    choices: [
      {
        textAr: 'تغطي طفلك بجسدك',
        textEn: 'You cover your child with your body',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -15,
        moraleEffect: 10,
        deathRisk: 0.08,
        injuryRisk: 0.15,
        messageAr: 'الغبار. الصمت. ثم بكاؤه تحتك. حي. أنت حي. هذا كل شيء.',
        messageEn: 'Dust. Silence. Then his crying beneath you. Alive. You are alive. That is everything.',
      },
      {
        textAr: 'تجري نحوه والانفجار يعصف',
        textEn: 'You run toward him as the blast tears through',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -20,
        moraleEffect: 15,
        deathRisk: 0.12,
        injuryRisk: 0.20,
        messageAr: 'وصلت إليه. يديك تحيطانه. الجسد يتألم. القلب مرتاح.',
        messageEn: 'You reached him. Your hands around him. The body hurts. The heart is at peace.',
      },
      {
        textAr: 'تتجمد — الجسد لا يستجيب',
        textEn: 'You freeze — the body does not respond',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: -15,
        deathRisk: 0.05,
        injuryRisk: 0.10,
        messageAr: 'ثانيتان. مررتا كعمر. ثم تحركت. الجسد أحياناً يخون. أنت لم تخن.',
        messageEn: 'Two seconds. They passed like a lifetime. Then you moved. The body sometimes betrays. You did not.',
      },
    ],
    realFactAr: 'غزة 2023-2024: أكثر من 85,000 طن من القنابل أُلقيت — أضعاف قنبلة هيروشيما.',
    realFactEn: 'Gaza 2023-2024: Over 85,000 tons of bombs dropped — multiple times the Hiroshima bomb.',
  },

  // ===== MONTH 9 =====
  {
    id: 'al_bahth_fi_al_rukam',
    month: 9,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'فقد',
    titleAr: 'البحث في الركام',
    titleEn: 'Searching the Rubble',
    storyAr: `أخوك لم يعد.\nالمنزل القديم قُصف الليلة الماضية.\nالناس يقولون لعله تحت الأنقاض.\nأنت تحفر بيديك في الحجارة.`,
    storyEn: `Your brother didn't come back.\nThe old house was struck last night.\nPeople say maybe he is under the rubble.\nYou dig with your bare hands through stone.`,
    choices: [
      {
        textAr: 'تحفر حتى تجده — مهما كان',
        textEn: 'You dig until you find him — whatever the outcome',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -20,
        moraleEffect: 5,
        deathRisk: 0.05,
        injuryRisk: 0.15,
        messageAr: 'يداك تنزفان. أصابعك كُسرت. لكنك وجدته. هذا الوجد له اسم يصعب نطقه.',
        messageEn: 'Your hands bleed. Your fingers broke. But you found him. This finding has a name that is hard to say.',
      },
      {
        textAr: 'تطلب من الآخرين المساعدة ثم تحفر معهم',
        textEn: 'You call others for help then dig together',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0.05,
        messageAr: 'جاء الجيران. جاء غرباء. حفروا معك. في الركام تُعاد الإنسانية.',
        messageEn: 'Neighbors came. Strangers came. They dug with you. In the rubble, humanity is rebuilt.',
      },
    ],
    realFactAr: 'غزة 2023-2024: آلاف لا يزالون مدفونين تحت الأنقاض — فرق الإنقاذ غير كافية.',
    realFactEn: 'Gaza 2023-2024: Thousands still buried under rubble — rescue teams insufficient.',
  },

  // ===== MONTH 10 =====
  {
    id: 'taboor_al_igatha',
    month: 10,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'قصف',
    titleAr: 'طابور الإغاثة',
    titleEn: 'The Aid Queue',
    storyAr: `الطابور طويل منذ الفجر.\nفجأة: أصوات في الهواء.\nإطلاق نار. الناس يركضون.\nشخص سقط قربك على الأرض.`,
    storyEn: `The queue has been long since dawn.\nSuddenly: sounds in the air.\nGunfire. People run.\nSomeone fell near you on the ground.`,
    choices: [
      {
        textAr: 'تنحني لتساعد من سقط',
        textEn: 'You bend down to help the one who fell',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: 10,
        deathRisk: 0.12,
        injuryRisk: 0.18,
        messageAr: 'كان حياً. ساعدته للوصول بعيداً. لم تحصل على الإغاثة. لكنك أنقذت شيئاً أهم.',
        messageEn: 'He was alive. You helped him get away. You didn\'t get the aid. But you saved something more important.',
      },
      {
        textAr: 'تجري مع الجميع — الغريزة تسيطر',
        textEn: 'You run with everyone — instinct takes over',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -15,
        moraleEffect: -10,
        deathRisk: 0.08,
        injuryRisk: 0.12,
        messageAr: 'ركضت. وصلت. لكن صورته على الأرض لن تغادر ذاكرتك.',
        messageEn: 'You ran. You made it. But his image on the ground will not leave your memory.',
      },
      {
        textAr: 'تقف مكانك — لا تعرف ماذا تفعل',
        textEn: 'You stand still — you don\'t know what to do',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -20,
        moraleEffect: -5,
        deathRisk: 0.15,
        injuryRisk: 0.20,
        messageAr: 'الخوف يجمّد. ليس جباناً من يجمّد. بل من رأى أكثر مما يحتمل.',
        messageEn: 'Fear freezes. The one who freezes is not a coward. But one who has seen more than can be borne.',
      },
    ],
    realFactAr: '29 فبراير 2024: مجزرة الدقيق — 112 شهيداً و750 جريحاً عند نقطة توزيع مساعدات.',
    realFactEn: 'Feb 29, 2024: The Flour Massacre — 112 killed and 750 wounded at an aid distribution point.',
  },

  // ===== MONTH 11 =====
  {
    id: 'al_layl_al_tawil',
    month: 11,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'نفس',
    titleAr: 'الليل الطويل',
    titleEn: 'The Long Night',
    storyAr: `حرارة طفلك ترتفع.\nلا دواء. لا مستشفى. لا طبيب.\nالليل طويل والأنفاس مقياسك الوحيد.\nتعد أنفاسه واحداً واحداً حتى الفجر.`,
    storyEn: `Your child\'s fever is rising.\nNo medicine. No hospital. No doctor.\nThe night is long and breath is your only measure.\nYou count his breaths one by one until dawn.`,
    choices: [
      {
        textAr: 'تبقى صاحياً طوال الليل تراقبه',
        textEn: 'You stay awake all night watching him',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الفجر جاء. حرارته انخفضت. أنت كنت هناك. هذا يكفي.',
        messageEn: 'Dawn came. His fever broke. You were there. That is enough.',
      },
      {
        textAr: 'تغمس قماشة بالماء وتضعها على جبهته طوال الليل',
        textEn: 'You soak a cloth in water and press it to his forehead all night',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: 12,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'القماشة الباردة بدلاً من الدواء. الحضور بدلاً من المستشفى. أحياناً الحب هو الطب.',
        messageEn: 'A cold cloth instead of medicine. Presence instead of hospital. Sometimes love is the medicine.',
      },
    ],
    showOnlyIfChildren: true,
    realFactAr: 'غزة 2023-2024: المستشفيات خرجت عن الخدمة — الأطفال يموتون من أمراض قابلة للعلاج.',
    realFactEn: 'Gaza 2023-2024: Hospitals went out of service — children dying from treatable diseases.',
  },

  // ===== MONTH 12 =====
  {
    id: 'al_nuzuh_al_thani',
    month: 12,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'وطن',
    titleAr: 'النزوح الثاني',
    titleEn: 'The Second Displacement',
    storyAr: `أوامر إخلاء مجدداً.\nهذه المرة من مكان نزوحك الأول.\nتنظر حولك: لا شيء تحمله.\nلأنك لا تملك شيئاً بعد الآن.`,
    storyEn: `Evacuation orders again.\nThis time from the place of your first displacement.\nYou look around: nothing to carry.\nBecause you own nothing anymore.`,
    choices: [
      {
        textAr: 'تمشي بلا تفكير — الجسد يتذكر',
        textEn: 'You walk without thinking — the body remembers',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -15,
        moraleEffect: -8,
        deathRisk: 0.06,
        injuryRisk: 0,
        messageAr: 'النزوح الثاني مختلف. لا بكاء. لا حسرة. فقط خطوات.',
        messageEn: 'The second displacement is different. No crying. No grief. Just steps.',
      },
      {
        textAr: 'تجلس لحظة قبل المغادرة وتنظر للخلف',
        textEn: 'You sit for a moment before leaving and look back',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: 5,
        deathRisk: 0.04,
        injuryRisk: 0,
        messageAr: 'نظرت للخيمة. للمكان الذي كان "البيت" شهراً واحداً. حتى المؤقت له وداع.',
        messageEn: 'You looked at the tent. At the place that was "home" for one month. Even the temporary deserves a goodbye.',
      },
      {
        textAr: 'ترفض المغادرة للحظات — حتى تجبرك',
        textEn: 'You refuse to leave for a moment — until forced',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -20,
        moraleEffect: 10,
        deathRisk: 0.10,
        injuryRisk: 0.12,
        messageAr: 'دقيقة من التمرد. في الحرب هذا يعني الكثير.',
        messageEn: 'One minute of defiance. In war this means a great deal.',
      },
    ],
    realFactAr: 'يناير 2024: النازحون في غزة يُنزحون مرة أخرى وثالثة ورابعة دون توقف.',
    realFactEn: 'January 2024: Displaced Gazans were displaced again and again without end.',
  },

  // ===== MONTH 13 =====
  {
    id: 'wadaa',
    month: 13,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'فقد',
    titleAr: 'وداع',
    titleEn: 'Farewell',
    storyAr: `مات أحد أفراد عائلتك.\nتقف أمامه الآن.\nلا كلمات كافية. لا وقت كافٍ.\nالعالم يستمر بالدوران والأصوات لا تتوقف.`,
    storyEn: `A member of your family has died.\nYou stand before them now.\nNo words are enough. No time is enough.\nThe world keeps turning and the sounds don\'t stop.`,
    choices: [
      {
        textAr: 'تضع يدك على صدره وتقرأ له بصوت خافت',
        textEn: 'You place your hand on his chest and recite for him in a low voice',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الكلمات ترتجف. لكنها خرجت. الأموات يسمعون الحب أيضاً.',
        messageEn: 'The words tremble. But they came out. The dead hear love too.',
      },
      {
        textAr: 'تجلس بجانبه صامتاً حتى يأتوا',
        textEn: 'You sit beside him in silence until they come',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: 3,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الصمت معه وداع. أحياناً الحضور هو كل ما تملكه.',
        messageEn: 'Silence with him is farewell. Sometimes presence is all you have.',
      },
      {
        textAr: 'تخرج. لا تستطيع البقاء في الغرفة معه.',
        textEn: 'You leave. You cannot stay in the room with him.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -15,
        moraleEffect: -10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الهروب من الفقد ليس ضعفاً. الجسد أحياناً يحمي القلب بطريقته.',
        messageEn: 'Running from loss is not weakness. The body sometimes protects the heart in its own way.',
      },
    ],
    realFactAr: 'غزة 2024: أكثر من 55,000 شهيد — معظمهم من النساء والأطفال.',
    realFactEn: 'Gaza 2024: Over 55,000 martyred — the majority were women and children.',
  },

  // ===== MONTH 14 =====
  {
    id: 'al_dafn_fi_al_hadeeka',
    month: 14,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'فقد',
    titleAr: 'الدفن في الحديقة',
    titleEn: 'Buried in the Garden',
    storyAr: `لا مقابر. المقابر نفسها قُصفت.\nأنت وأخوك تحملان المجرفة.\nالحديقة التي كانت تضحك بالورد\nسوف تحضن من أحببته اليوم.`,
    storyEn: `No cemeteries. The cemeteries themselves were bombed.\nYou and your brother carry the shovel.\nThe garden that once laughed with flowers\nwill embrace the one you loved today.`,
    choices: [
      {
        textAr: 'تحفران معاً بصمت حتى يُكتمل',
        textEn: 'You dig together in silence until it\'s done',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -15,
        moraleEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الصمت كان كاملاً. العمل كان الصلاة. أنهيتما ما يجب.',
        messageEn: 'The silence was complete. The work was the prayer. You finished what must be done.',
      },
      {
        textAr: 'تحفر وأنت تتكلم معه كأنه يسمع',
        textEn: 'You dig while talking to him as though he hears',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'قلت له كل ما لم تقله في حياته. ربما الموت هو الوقت الوحيد الذي لا يقاطعك فيه أحد.',
        messageEn: 'You told him everything you never said in his life. Perhaps death is the only time no one interrupts you.',
      },
    ],
    realFactAr: 'غزة 2024: دُفن الشهداء في حدائق المنازل والملاعب والشوارع لغياب المقابر.',
    realFactEn: 'Gaza 2024: Martyrs buried in home gardens, playgrounds, and streets due to absence of cemeteries.',
  },

  // ===== MONTH 15 =====
  {
    id: 'soal_tifl',
    month: 15,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'فقد',
    titleAr: 'سؤال طفل',
    titleEn: 'A Child\'s Question',
    storyAr: `طفلك يسأل:\n"وين رح [اسم من رحل]؟ متى يرجع؟"\nأنت لا تستطيع أن تتكلم.\nلا تستطيع أن تبكي أمامه.\nولا تستطيع الكذب بعد الآن.`,
    storyEn: `Your child asks:\n"Where did [the one who left] go? When will they come back?"\nYou cannot speak.\nYou cannot cry in front of him.\nAnd you can no longer lie.`,
    choices: [
      {
        textAr: '"راح عند الله. في مكان لا يؤلم فيه شيء."',
        textEn: '"They went to God. A place where nothing hurts."',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'قبل هذا بصمت. ثم سأل: "بيشوفنا من هناك؟" قلت: "نعم." وآمنت بما قلت.',
        messageEn: 'He accepted this in silence. Then asked: "Can they see us from there?" You said: "Yes." And believed what you said.',
      },
      {
        textAr: 'لا تجيب. تأخذه في حضنك وتبكيان معاً.',
        textEn: 'You don\'t answer. You take him in your arms and you both cry.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'البكاء المشترك ليس ضعفاً. هو اعتراف بأن من رحل كان يستحق أن يُبكى عليه.',
        messageEn: 'Shared crying is not weakness. It is acknowledgment that the one who left deserved to be mourned.',
      },
    ],
    showOnlyIfChildren: true,
    realFactAr: 'UNICEF 2024: أكثر من 17,000 طفل يتيم في غزة فقدوا أحد والديهم أو كليهما.',
    realFactEn: 'UNICEF 2024: Over 17,000 children orphaned in Gaza, having lost one or both parents.',
  },

  // ===== MONTH 16 =====
  {
    id: 'al_kutub',
    month: 16,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'ذاكرة',
    titleAr: 'الكتب',
    titleEn: 'The Books',
    storyAr: `البرد شديد الليلة.\nالأطفال يرتجفون تحت الأغطية الرقيقة.\nأمامك كومة من الكتب — كتب المدرسة، رواية أحببتها، دفاتر قديمة.\nالنار تحتاج وقوداً.`,
    storyEn: `The cold is fierce tonight.\nChildren shiver under thin blankets.\nBefore you a pile of books — school books, a novel you loved, old notebooks.\nThe fire needs fuel.`,
    choices: [
      {
        textAr: 'تحرق الكتب لتدفئة الأطفال',
        textEn: 'You burn the books to warm the children',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: -10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الأطفال دفئوا. الكتب احترقت. الكلمات كانت هنا وذهبت. الدفء بقي.',
        messageEn: 'The children warmed. The books burned. The words were here and are gone. Warmth remained.',
      },
      {
        textAr: 'تبحث عن شيء آخر للإحراق وتُبقي الكتب',
        textEn: 'You look for something else to burn and keep the books',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'وجدت ألواح خشب قديمة. الكتب بقيت. أحياناً المقاومة تكون في ما لا تحرقه.',
        messageEn: 'You found old wooden boards. The books remained. Sometimes resistance is in what you don\'t burn.',
      },
      {
        textAr: 'تحرق بعضها وتُبقي الكتب التي تحبها',
        textEn: 'You burn some and keep the ones you love',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: -3,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'اخترت. بعض الكتب صارت نار. بعضها بقي ذاكرة. الحياة كلها اختيار بين ما يحترق وما يبقى.',
        messageEn: 'You chose. Some books became fire. Some remained memory. All of life is a choice between what burns and what remains.',
      },
    ],
    realFactAr: 'شتاء 2023-2024: نازحون في غزة أحرقوا كتبهم وملابسهم للتدفئة في غياب الوقود.',
    realFactEn: 'Winter 2023-2024: Displaced people in Gaza burned their books and clothes for warmth in the absence of fuel.',
  },

  // ===== MONTH 17 =====
  {
    id: 'al_miraya',
    month: 17,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'نفس',
    titleAr: 'المرآة',
    titleEn: 'The Mirror',
    storyAr: `بالصدفة وجدت مرآة كسرها في ركام بيت مجاور.\nنظرت إليها لأول مرة منذ شهور.\nالوجه الذي رأيته لم تكن تعرفه تماماً.`,
    storyEn: `By chance you found a broken mirror in the rubble of a neighbor\'s house.\nYou looked at yourself for the first time in months.\nThe face you saw was one you didn\'t quite know.`,
    choices: [
      {
        textAr: 'تنظر طويلاً. تحاول أن تتعرف على نفسك.',
        textEn: 'You look for a long time. You try to recognize yourself.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الوجه نفسه. لكن شيئاً تغيّر خلف العيون. ليس أقل. مختلف.',
        messageEn: 'The same face. But something changed behind the eyes. Not less. Different.',
      },
      {
        textAr: 'تكسر المرآة مجدداً وتمشي',
        textEn: 'You break the mirror again and walk away',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: -8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'لم تكن مستعداً لذلك اللقاء. ربما لاحقاً. ربما بعد انتهاء هذا كله.',
        messageEn: 'You weren\'t ready for that meeting. Perhaps later. Perhaps after all this ends.',
      },
      {
        textAr: 'تمسح وجهك بالماء وتنظف ما تستطيع',
        textEn: 'You wash your face with water and clean what you can',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'فعل بسيط. لكنه اعتراف بأن الجسد يستحق العناية حتى في الحرب.',
        messageEn: 'A simple act. But an acknowledgment that the body deserves care even in war.',
      },
    ],
    realFactAr: 'دراسات الصدمة: فقدان الهوية الشخصية من أشد آثار النزوح المطوّل على الإنسان.',
    realFactEn: 'Trauma studies: Loss of personal identity is among the most severe effects of prolonged displacement.',
  },

  // ===== MONTH 18 =====
  {
    id: 'al_sabah_al_farig',
    month: 18,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'نفس',
    titleAr: 'الصباح الفارغ',
    titleEn: 'The Empty Morning',
    storyAr: `أول يوم بلا عمل. بلا روتين. بلا هدف.\nاستيقظت مبكراً كعادتك.\nلكن لا يوجد مكان تذهب إليه.\nولا شيء تفعله سوى الجلوس والانتظار.\nانتظار ماذا؟ لا تعرف.`,
    storyEn: `The first day without work. Without routine. Without purpose.\nYou woke up early as usual.\nBut there is nowhere to go.\nNothing to do but sit and wait.\nWait for what? You don\'t know.`,
    choices: [
      {
        textAr: 'تبدأ يوماً بلا خطة — تمشي بلا هدف',
        textEn: 'You begin a day with no plan — you walk with no destination',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: -8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'مشيت. رأيت وجوهاً تعرفها. كلكم تبحثون عن نفس الشيء: شيء يملأ الوقت.',
        messageEn: 'You walked. You saw faces you know. All of you searching for the same thing: something to fill the time.',
      },
      {
        textAr: 'تعلّم أحد الأطفال شيئاً — أي شيء',
        textEn: 'You teach one of the children something — anything',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 15,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'علّمته كيف يقرأ الكلمات. عيناه أضاءتا. أنت من كان بحاجة لهذا الدرس أيضاً.',
        messageEn: 'You taught him to read words. His eyes lit up. You were the one who needed this lesson too.',
      },
      {
        textAr: 'تجلس وتكتب — أو تحاول',
        textEn: 'You sit and write — or try to',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'بدأت بجملة واحدة. ثم توقفت. لكن الجملة الأولى كتبت نفسها: "اليوم..."',
        messageEn: 'You started with one sentence. Then stopped. But the first sentence wrote itself: "Today..."',
      },
    ],
    realFactAr: 'غزة 2024: 80% من القوى العاملة فقدت أعمالها — البطالة القسرية تضرب الكرامة.',
    realFactEn: 'Gaza 2024: 80% of the workforce lost their jobs — forced unemployment strikes at dignity.',
  },

  // ===== MONTH 19 =====
  {
    id: 'al_jamiaa',
    month: 19,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'ذاكرة',
    titleAr: 'الجامعة',
    titleEn: 'The University',
    storyAr: `أخبرك أحدهم بالصدفة:\nالجامعة التي درست فيها دُمّرت.\nرسالتك التي أمضيت عليها ثلاث سنوات\nصارت تحت الركام.\nكل تلك الليالي. كل ذلك الأمل.`,
    storyEn: `Someone told you by chance:\nThe university where you studied was destroyed.\nYour thesis that you spent three years on\nis now under rubble.\nAll those nights. All that hope.`,
    choices: [
      {
        textAr: 'تصمت وتمشي. لا تعلق.',
        textEn: 'You go silent and walk away. No comment.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: -12,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الصمت أحياناً هو الصرخة الأعلى. أحيانٌ لا تملك حتى الكلمات لتصف الخسارة.',
        messageEn: 'Silence is sometimes the loudest scream. Sometimes you don\'t even have the words to describe the loss.',
      },
      {
        textAr: 'تقول: "الرسالة في رأسي. لم تحرق."',
        textEn: 'You say: "The thesis is in my head. It wasn\'t burned."',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: 12,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'قلتها لنفسك أكثر مما قلتها له. المعرفة في الذاكرة لا في الورق.',
        messageEn: 'You said it to yourself more than to him. Knowledge is in memory not in paper.',
      },
      {
        textAr: 'تبكي. أول مرة تبكي منذ أشهر.',
        textEn: 'You cry. The first time you\'ve cried in months.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'دموع على ورق. على مستقبل. على ثلاث سنوات. أحياناً البكاء هو الطريق الوحيد للمضي قدماً.',
        messageEn: 'Tears for paper. For a future. For three years. Sometimes crying is the only path forward.',
      },
    ],
    realFactAr: 'غزة 2024: 12 جامعة دُمّرت — نظام التعليم العالي محا تماماً.',
    realFactEn: 'Gaza 2024: 12 universities destroyed — the entire higher education system erased.',
  },

  // ===== MONTH 20 =====
  {
    id: 'al_tifl_la_yalb',
    month: 20,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'نفس',
    titleAr: 'الطفل لا يلعب',
    titleEn: 'The Child Who Doesn\'t Play',
    storyAr: `طفلك يجلس في الزاوية.\nلا يتكلم. لا يلعب. لا يبكي.\nفقط يجلس وينظر لشيء لا تراه أنت.\nهذا الصمت أخوف عليك من كل قصف.`,
    storyEn: `Your child sits in the corner.\nDoesn\'t speak. Doesn\'t play. Doesn\'t cry.\nJust sits and stares at something you cannot see.\nThis silence frightens you more than any bombing.`,
    choices: [
      {
        textAr: 'تجلس بجانبه بصمت حتى ينظر إليك',
        textEn: 'You sit beside him in silence until he looks at you',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'بعد وقت طويل نظر إليك. لم يتكلم. لكنه لم يعد وحيداً في مكانه الداخلي.',
        messageEn: 'After a long time he looked at you. Didn\'t speak. But he was no longer alone in his inner place.',
      },
      {
        textAr: 'تحاول تشجيعه على اللعب — تصنع لعبة من لا شيء',
        textEn: 'You try to encourage him to play — you make a toy from nothing',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 12,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'صنعت طائرة من ورقة قديمة. نظر إليها. مدّ يده ببطء. هذا هو الأمل — بطيء وحذر.',
        messageEn: 'You made a plane from an old piece of paper. He looked at it. Slowly reached his hand out. That is hope — slow and cautious.',
      },
      {
        textAr: 'تحضنه بشدة دون تفسير',
        textEn: 'You hold him tightly without explanation',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'شعر بك. جسده ارتخى شيئاً ما. بعض الجروح تُعالَج باللمس.',
        messageEn: 'He felt you. His body relaxed a little. Some wounds are healed by touch.',
      },
    ],
    showOnlyIfChildren: true,
    realFactAr: 'UNICEF 2024: أكثر من مليون طفل في غزة يعانون من صدمة نفسية حادة تتطلب دعماً متخصصاً.',
    realFactEn: 'UNICEF 2024: Over one million children in Gaza suffering from acute trauma requiring specialized support.',
  },

  // ===== MONTH 21 =====
  {
    id: 'ard_al_hijra',
    month: 21,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'وطن',
    titleAr: 'عرض الهجرة',
    titleEn: 'The Migration Offer',
    storyAr: `جاءك شخص تثق به.\n"فيه طريقة للخروج. مكلفة. لكن ممكنة."\nلأول مرة منذ أشهر فكرت فعلاً بالرحيل.\nجلست طويلاً تحمل هذا السؤال.`,
    storyEn: `Someone you trust came to you.\n"There is a way out. Expensive. But possible."\nFor the first time in months you genuinely thought about leaving.\nYou sat a long time holding this question.`,
    choices: [
      {
        textAr: 'ترفض. هذه أرضك.',
        textEn: 'You refuse. This is your land.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'قلت لا. وأغلقت الباب الداخلي على هذا السؤال. لكنه لم ينس أن يطرق أحياناً.',
        messageEn: 'You said no. And closed the inner door on this question. But it didn\'t forget to knock sometimes.',
      },
      {
        textAr: 'تفكر جدياً لأول مرة',
        textEn: 'You think seriously for the first time',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'لم تقل نعم. لم تقل لا. لكنك لم تعد تسخر ممن يفكرون في المغادرة.',
        messageEn: 'You didn\'t say yes. Didn\'t say no. But you no longer mocked those thinking of leaving.',
      },
      {
        textAr: 'تقرر البقاء — لكن تبقي الفكرة في الخلفية',
        textEn: 'You decide to stay — but keep the idea in the background',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 3,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'البقاء قرار. لكنه لم يعد نفس القرار الذي اتخذته في اليوم الأول.',
        messageEn: 'Staying is a decision. But it\'s no longer the same decision you made on the first day.',
      },
    ],
    realFactAr: 'غزة 2024: تكلّف إخراج الأسرة الواحدة ما بين 5,000 و30,000 دولار — معظمهم لا يملك ذلك.',
    realFactEn: 'Gaza 2024: Getting a family out cost between $5,000 and $30,000 — most don\'t have it.',
  },

  // ===== MONTH 22 =====
  {
    id: 'wadaa_al_jar',
    month: 22,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'فقد',
    titleAr: 'وداع الجار',
    titleEn: 'Goodbye to the Neighbor',
    storyAr: `أبو سامر قرر الرحيل.\nجمع أولاده وزوجته وقال: "لا مستقبل هنا للأولاد."\nتقف أمامه الآن لتودعه.\nلا تعرف إن كنت ستلتقيان مجدداً.`,
    storyEn: `Abu Samer decided to leave.\nHe gathered his children and wife and said: "There\'s no future here for the kids."\nYou stand before him now to say goodbye.\nYou don\'t know if you will ever meet again.`,
    choices: [
      {
        textAr: 'تحضنه طويلاً وتقول: "الله يوفقكم"',
        textEn: 'You hold him long and say: "God be with you"',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'مشى. التفت مرة. أكمل. خلف كل مغادر جرح جديد لمن بقي.',
        messageEn: 'He walked. Turned once. Continued. Behind every departure is a new wound for those who remain.',
      },
      {
        textAr: 'تقول له: "محق. اذهب ولا تنظر للخلف."',
        textEn: 'You tell him: "You\'re right. Go and don\'t look back."',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: -8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'قلت ما تمنيت أن يُقال لك. ربما يوماً ما.',
        messageEn: 'You said what you wished someone would say to you. Perhaps someday.',
      },
      {
        textAr: 'لا تقول شيئاً. تنظر إليه وتومئ.',
        textEn: 'You say nothing. You look at him and nod.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: -3,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الإيماءة قالت كل شيء. بعض اللحظات أكبر من الكلمات.',
        messageEn: 'The nod said everything. Some moments are bigger than words.',
      },
    ],
    realFactAr: 'غزة 2024: مئات الآلاف غادروا القطاع — أحياء أصبحت خالية إلا من أصوات الريح.',
    realFactEn: 'Gaza 2024: Hundreds of thousands left the Strip — neighborhoods became empty except for the sound of wind.',
  },

  // ===== MONTH 23 =====
  {
    id: 'al_kitaba_ala_al_jidar',
    month: 23,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'ذاكرة',
    titleAr: 'الكتابة على الجدار',
    titleEn: 'Writing on the Wall',
    storyAr: `وجدت قطعة فحم أسود.\nأمامك جدار خيمة أو حائط ركام.\nلا أحد يراك.\nشيء في داخلك يريد أن يكتب.`,
    storyEn: `You found a piece of black charcoal.\nBefore you a tent wall or a rubble wall.\nNo one is watching.\nSomething inside you wants to write.`,
    choices: [
      {
        textAr: 'تكتب اسم من رحل',
        textEn: 'You write the name of the one who left',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الاسم على الجدار. أصبح أكبر من حجمه. الكتابة نوع من الدفن الكريم.',
        messageEn: 'The name on the wall. It became larger than its size. Writing is a kind of dignified burial.',
      },
      {
        textAr: 'تكتب تاريخ اليوم وعدد من تبقّى معك',
        textEn: 'You write today\'s date and how many remain with you',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الأرقام على الجدار. هذا السجل أمانة. يوماً ما سيقرأه شخص ويعرف أنكم كنتم هنا.',
        messageEn: 'Numbers on the wall. This record is a trust. One day someone will read it and know you were here.',
      },
      {
        textAr: 'تكتب كلمة واحدة فقط: "نحن هنا"',
        textEn: 'You write only one word: "We are here"',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 12,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: '"نحن هنا." ثلاث كلمات ضد كل من أراد أن يمحوكم.',
        messageEn: '"We are here." Three words against all who wanted to erase you.',
      },
    ],
    realFactAr: 'شهادات من غزة: أهالٍ يكتبون أسماء أبنائهم على جدران منازل مهدّمة حتى لا تُنسى.',
    realFactEn: 'Testimonies from Gaza: Families writing their children\'s names on walls of destroyed homes so they won\'t be forgotten.',
  },

  // ===== MONTH 24 =====
  {
    id: 'add_al_ayyam',
    month: 24,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'ذاكرة',
    titleAr: 'عدّ الأيام',
    titleEn: 'Counting the Days',
    storyAr: `لاحظت الخطوط على الجدار.\nبدأتها ذات يوم دون أن تقرر.\nلكل خط يوم مرّ.\nتحسب: أربعة وعشرون شهراً.\nلماذا تعد؟ لا تعرف تماماً.`,
    storyEn: `You noticed the lines on the wall.\nYou started them one day without deciding.\nEach line is a day that passed.\nYou count: twenty-four months.\nWhy do you count? You don\'t entirely know.`,
    choices: [
      {
        textAr: 'تضيف خطاً اليوم أيضاً',
        textEn: 'You add a line today too',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الخط الجديد قال: "ها أنا لا أزال هنا." هذا كاف.',
        messageEn: 'The new line said: "Here I am, still here." That is enough.',
      },
      {
        textAr: 'تمسح الخطوط كلها',
        textEn: 'You erase all the lines',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الأيام لم تُمسح. فقط الأثر على الجدار. الزمن لا يُمسح بيد.',
        messageEn: 'The days weren\'t erased. Only the marks on the wall. Time cannot be wiped away by hand.',
      },
      {
        textAr: 'تترك الخطوط وتجلس تنظر إليها',
        textEn: 'You leave the lines and sit looking at them',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'كل خط حياة كاملة. يوم كامل عشته. هذا دليل أنك مقاوم بطريقتك.',
        messageEn: 'Each line is a whole life. A whole day you lived. This is proof that you resist in your own way.',
      },
    ],
    realFactAr: 'شهادات موثقة: نازحون في غزة يعدّون الأيام على جدران الخيام دليلاً على أنهم لا يزالون أحياء.',
    realFactEn: 'Documented testimonies: Displaced people in Gaza count days on tent walls as proof they are still alive.',
  },

  // ===== MONTH 25 =====
  {
    id: 'ishaat_waqf_al_nar',
    month: 25,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'صمود',
    titleAr: 'إشاعة وقف النار',
    titleEn: 'The Ceasefire Rumor',
    storyAr: `قال أحدهم: "سمعت إنه وقف إطلاق نار بكرة."\nشيء في صدرك قفز قبل أن يأذن عقلك.\nثم صمت الراديو. ثم القصف عاد.\nالأمل الكاذب أقسى من اليأس الصادق.`,
    storyEn: `Someone said: "I heard there\'s a ceasefire tomorrow."\nSomething in your chest leaped before your mind gave permission.\nThen the radio went silent. Then the bombing returned.\nFalse hope is harsher than honest despair.`,
    choices: [
      {
        textAr: 'تحاول ألا تصدق. لكن قلبك لا يسمع.',
        textEn: 'You try not to believe. But your heart doesn\'t listen.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: -15,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الأمل الكاذب يترك جرحاً أعمق من الأمل الغائب. تعلمت درساً مؤلماً.',
        messageEn: 'False hope leaves a wound deeper than absent hope. You learned a painful lesson.',
      },
      {
        textAr: 'تقول للأطفال لا شيء — تنتظر أنت وحدك',
        textEn: 'You tell the children nothing — you wait alone',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -8,
        moraleEffect: -8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'حملت الخبر وحدك. القصف عاد. حملت الخيبة وحدك أيضاً.',
        messageEn: 'You carried the news alone. The bombing returned. You carried the disappointment alone too.',
      },
    ],
    realFactAr: 'مارس 2025: انهيار محادثات الهدنة مرات متعددة أثناء تصاعد القصف على المخيمات.',
    realFactEn: 'March 2025: Ceasefire talks collapsed multiple times while bombing on camps intensified.',
  },

  // ===== MONTH 26 =====
  {
    id: 'al_marad',
    month: 26,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'نفس',
    titleAr: 'المرض',
    titleEn: 'The Illness',
    storyAr: `وباء في المخيم.\nطفلك يحمل الأعراض منذ يومين.\nلا طبيب. لا عيادة. لا دواء.\nأنت وحدك والليل طويل.`,
    storyEn: `An epidemic in the camp.\nYour child has shown symptoms for two days.\nNo doctor. No clinic. No medicine.\nYou alone and the night is long.`,
    choices: [
      {
        textAr: 'تبقى بجانبه. تراقب. تصلي.',
        textEn: 'You stay beside him. You watch. You pray.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -15,
        moraleEffect: 5,
        deathRisk: 0.08,
        injuryRisk: 0,
        messageAr: 'الليل طويل. الحرارة ترتفع وتنخفض. أنت لا تتزحزح.',
        messageEn: 'The night is long. The fever rises and falls. You don\'t move.',
      },
      {
        textAr: 'تبحث في المخيم عن أي شخص لديه دواء أو خبرة',
        textEn: 'You search the camp for anyone with medicine or knowledge',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: 10,
        deathRisk: 0.05,
        injuryRisk: 0,
        messageAr: 'وجدت ممرضة فقدت عيادتها. جلست معكم ساعتين. أحياناً الناس هم الدواء.',
        messageEn: 'You found a nurse who lost her clinic. She sat with you for two hours. Sometimes people are the medicine.',
      },
    ],
    showOnlyIfChildren: true,
    realFactAr: 'غزة 2024: التهاب الكبد والجرب والكوليرا تفشّت في مخيمات مكتظة بلا صرف صحي.',
    realFactEn: 'Gaza 2024: Hepatitis, scabies, and cholera spread through overcrowded camps with no sanitation.',
  },

  // ===== MONTH 27 =====
  {
    id: 'al_fajr',
    month: 27,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'صمود',
    titleAr: 'الفجر',
    titleEn: 'Dawn',
    storyAr: `سهرت الليل كله تراقب أنفاسه.\nلا نوم. لا راحة. كل ثانية حساب.\nثم جاء الفجر.\nالحرارة نزلت. أنفاسه هادئة.\nهو ينام. أنت تنظر إليه في الضوء الأول.`,
    storyEn: `You stayed up all night watching his breathing.\nNo sleep. No rest. Every second counted.\nThen dawn came.\nThe fever broke. His breathing is calm.\nHe sleeps. You look at him in the first light.`,
    choices: [
      {
        textAr: 'تبكي بصمت من الارتياح',
        textEn: 'You cry quietly from relief',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: 20,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الدموع من الفرح هي أخف أنواع البكاء. هذا الصباح أثقل من ألف ليلة.',
        messageEn: 'Tears of joy are the lightest kind of crying. This morning outweighs a thousand nights.',
      },
      {
        textAr: 'تجلس فقط وتنظر إليه يتنفس',
        textEn: 'You just sit and watch him breathe',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: 18,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'التنفس. أبسط الأشياء وأثمنها. لم تكن تعرف ذلك قبل الحرب.',
        messageEn: 'Breath. The simplest of things and the most precious. You didn\'t know that before the war.',
      },
    ],
    showOnlyIfChildren: true,
    realFactAr: 'الأطباء في غزة: أولياء الأمور يسهرون لياليهم يراقبون أنفاس أطفالهم — الخوف يصبح يقظة.',
    realFactEn: 'Doctors in Gaza: Parents stay awake all night watching their children breathe — fear becomes vigilance.',
  },

  // ===== MONTH 28 =====
  {
    id: 'shay_min_al_bayt',
    month: 28,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'ذاكرة',
    titleAr: 'شيء من البيت',
    titleEn: 'Something from Home',
    storyAr: `مررت قرب ركام بيتك القديم.\nبين الحجارة والتراب رأيت شيئاً تعرفه.\nشيئاً صغيراً لا يساوي شيئاً\nلكنه كان في بيتك. كان لك.`,
    storyEn: `You passed near the rubble of your old home.\nBetween the stones and dust you saw something you recognize.\nA small thing worth nothing\nbut it was in your home. It was yours.`,
    choices: [
      {
        textAr: 'تأخذه. تحمله معك.',
        textEn: 'You take it. You carry it with you.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 12,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'وضعته في جيبك. في الليل أخرجته وضحكت وبكيت. الذاكرة المادية هي التي تقاوم النسيان.',
        messageEn: 'You put it in your pocket. That night you took it out and laughed and cried. Material memory is what resists forgetting.',
      },
      {
        textAr: 'تتركه. هذا المكان لم يعد يشبه البيت.',
        textEn: 'You leave it. This place no longer resembles home.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: -8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'تركته في الركام. ربما لأنك لا تريد أن تحمل ثقل ما ضاع. ربما لأن التركه أرحم.',
        messageEn: 'You left it in the rubble. Perhaps because you don\'t want to carry the weight of what was lost. Perhaps because leaving it is more merciful.',
      },
      {
        textAr: 'تحمله ثم تضعه مجدداً — لا تستطيع البت',
        textEn: 'You pick it up then put it down again — you can\'t decide',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: 5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'بعض اللحظات لا تنتهي بقرار. ووقفت هناك في المنتصف. مكان كثيرون وقفوا فيه.',
        messageEn: 'Some moments don\'t end with a decision. You stood there in the middle. A place many have stood.',
      },
    ],
    realFactAr: 'شهادات من غزة: ناجون يبحثون بين الأنقاض عن صور أو مفاتيح أو أي شيء يثبت أن حياتهم كانت موجودة.',
    realFactEn: 'Testimonies from Gaza: Survivors search through rubble for photos, keys, anything that proves their lives existed.',
  },

  // ===== MONTH 29 =====
  {
    id: 'al_samt',
    month: 29,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'قصف',
    titleAr: 'الصمت',
    titleEn: 'The Silence',
    storyAr: `لأول مرة منذ أشهر لا تسمع شيئاً.\nلا طائرات. لا انفجارات. لا صراخ.\nصمت حقيقي.\nلكن هذا الصمت يُخيفك أكثر من القصف.\nلا تعرف ما يعنيه.`,
    storyEn: `For the first time in months you hear nothing.\nNo planes. No explosions. No screaming.\nReal silence.\nBut this silence frightens you more than the bombing.\nYou don\'t know what it means.`,
    choices: [
      {
        textAr: 'تخرج لترى بعينيك ما يجري',
        textEn: 'You go out to see with your own eyes what is happening',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 5,
        deathRisk: 0.03,
        injuryRisk: 0,
        messageAr: 'الناس في الشارع صامتون أيضاً. كلكم تنظرون للسماء. كلكم لا تصدقون.',
        messageEn: 'The people in the street are silent too. All of you looking at the sky. None of you believing.',
      },
      {
        textAr: 'تبقى داخل الخيمة. الصمت فخ في بعض الأحيان.',
        textEn: 'You stay inside the tent. Silence is sometimes a trap.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'بقيت. استمر الصمت. الخوف من الصمت جرح لم تكن تعرفه قبل الحرب.',
        messageEn: 'You stayed. The silence continued. The fear of silence is a wound you didn\'t know before the war.',
      },
      {
        textAr: 'تستيقظ الأطفال وتجلسون معاً في الهدوء',
        textEn: 'You wake the children and sit together in the quiet',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'جلستم في الصمت معاً. لأول مرة منذ أشهر تسمع أنفاسهم بلا صوت آخر فوقها.',
        messageEn: 'You sat in silence together. For the first time in months you hear their breathing without any other sound above it.',
      },
    ],
    realFactAr: 'شهادات نفسية من مناطق حرب: الصمت بعد القصف المطوّل يُصيب بالرهاب والقلق الشديد.',
    realFactEn: 'Psychological testimonies from war zones: Silence after prolonged bombing causes phobia and severe anxiety.',
  },

  // ===== MONTH 30 =====
  {
    id: 'man_tabaqqa',
    month: 30,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'فقد',
    titleAr: 'من تبقّى',
    titleEn: 'Who Remains',
    storyAr: `ثلاثون شهراً.\nجلست اليوم وفكرت في كل من كان معك في البداية.\nتعدّهم بالاسم واحداً واحداً.\nبعضهم هنا. بعضهم رحل. بعضهم...`,
    storyEn: `Thirty months.\nToday you sat and thought of everyone who was with you at the beginning.\nYou count them by name one by one.\nSome are here. Some left. Some...`,
    choices: [
      {
        textAr: 'تقول كل اسم بصوت عالٍ',
        textEn: 'You say every name out loud',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الأسماء ملأت الهواء. بعضها أوجع. لكنها كلها كانت هنا. أنت تذكر. هذا كافٍ.',
        messageEn: 'The names filled the air. Some hurt. But they were all here. You remember. That is enough.',
      },
      {
        textAr: 'تكتبهم على الورق — لا تريدهم في رأسك فقط',
        textEn: 'You write them on paper — you don\'t want them only in your head',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'ورقة مكتوب عليها أسماء. ليست قائمة خسائر. هي قائمة حب.',
        messageEn: 'A paper with names written on it. Not a loss list. It is a love list.',
      },
      {
        textAr: 'تتوقف قبل الانتهاء. بعض الأسماء لا تستطيع قولها.',
        textEn: 'You stop before finishing. Some names you cannot say.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'توقفت. بعض الأسماء أثقل من أن تحملها الكلمات. هذا ليس نسياناً. هذا أشد الحب.',
        messageEn: 'You stopped. Some names are heavier than words can carry. This is not forgetting. This is the most intense love.',
      },
    ],
    realFactAr: 'غزة 2026: متوسط الأسرة الغزاوية فقد أكثر من ثلاثة أفراد خلال فترة الحرب.',
    realFactEn: 'Gaza 2026: The average Gazan family lost more than three members during the war.',
  },

  // ===== MONTH 31 =====
  {
    id: 'waqf_al_nar',
    month: 31,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'صمود',
    titleAr: 'وقف النار',
    titleEn: 'The Ceasefire',
    storyAr: `قالوا هذه المرة إنه حقيقي.\nوقف إطلاق نار. رسمي. موثّق.\nالراديو يؤكد. الناس في الشارع.\nلكن جسدك لا يصدق بعد.\nالأذنان تنتظران الصوت الذي تعلمتا الخوف منه.`,
    storyEn: `They said this time it\'s real.\nA ceasefire. Official. Documented.\nThe radio confirms. People are in the street.\nBut your body doesn\'t believe yet.\nYour ears wait for the sound they learned to fear.`,
    choices: [
      {
        textAr: 'تخرج. تنظر للسماء.',
        textEn: 'You go out. You look at the sky.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: 15,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'السماء فارغة. لا طيف يتحرك فيها. لأول مرة منذ سنتين تنظر للفوق دون خوف.',
        messageEn: 'The sky is empty. No shadow moves in it. For the first time in two years you look upward without fear.',
      },
      {
        textAr: 'تبقى في الخيمة. الأمل أخطر من القصف.',
        textEn: 'You stay in the tent. Hope is more dangerous than bombing.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'بقيت تنتظر. الصمت استمر. شيئاً فشيئاً بدأ جسدك يصدق ما تأبى عقلك قبوله.',
        messageEn: 'You stayed waiting. The silence continued. Little by little your body began to believe what your mind refused to accept.',
      },
      {
        textAr: 'تصحو الأطفال وتقول لهم: "انتهى"',
        textEn: 'You wake the children and tell them: "It\'s over"',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: 20,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'نظروا إليك بعيون لا تعرف ماذا يعني "انتهى". أنت أيضاً لا تعرف تماماً. لكنك قلتها.',
        messageEn: 'They looked at you with eyes that don\'t know what "it\'s over" means. You don\'t entirely know either. But you said it.',
      },
    ],
    realFactAr: 'يناير 2025: وقف إطلاق النار الأول — 376,000 نازح بدأوا العودة للشمال.',
    realFactEn: 'January 2025: The first ceasefire — 376,000 displaced began returning north.',
  },

  // ===== MONTH 32 =====
  {
    id: 'al_awda_lil_hayy',
    month: 32,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'وطن',
    titleAr: 'العودة للحيّ',
    titleEn: 'Return to the Neighborhood',
    storyAr: `أخذت طريقك للحيّ القديم.\nالشارع الذي ترعرعت فيه.\nالمسجد. المدرسة. بيت الجيران.\nكل شيء... غير موجود.\nالأشجار التي تعرفها صارت جذوراً في التراب.`,
    storyEn: `You took the road to your old neighborhood.\nThe street where you grew up.\nThe mosque. The school. The neighbor\'s house.\nEverything... is gone.\nThe trees you knew became roots in the ground.`,
    choices: [
      {
        textAr: 'تقف في وسط الركام وتنظر.',
        textEn: 'You stand in the middle of the rubble and look.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -10,
        moraleEffect: -15,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'لا كلمات. الركام أمامك. الذاكرة خلفك. أنت في المنتصف.',
        messageEn: 'No words. Rubble before you. Memory behind you. You in the middle.',
      },
      {
        textAr: 'تبدأ تتعرف على الأماكن رغم الدمار',
        textEn: 'You start recognizing places despite the destruction',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'هذه درجات بيتنا. هذا بلاط المطبخ. لا يزال هناك. الذاكرة أقوى من القصف.',
        messageEn: 'These are our house steps. This is the kitchen tile. Still there. Memory is stronger than bombing.',
      },
      {
        textAr: 'تجلس على حجر وتبكي. لأول مرة بصوت.',
        textEn: 'You sit on a stone and cry. For the first time out loud.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: -5,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الصوت خرج. كان يحتاج أن يخرج. الركام سمعه. الهواء حمله. ربما يكفي.',
        messageEn: 'The sound came out. It needed to come out. The rubble heard it. The air carried it. Perhaps that is enough.',
      },
    ],
    realFactAr: 'مارس 2025: العائدون إلى شمال غزة وجدوا 90% من المباني مدمرة أو متضررة.',
    realFactEn: 'March 2025: Those returning to northern Gaza found 90% of buildings destroyed or damaged.',
  },

  // ===== MONTH 33 =====
  {
    id: 'al_dhakira_al_maddiya',
    month: 33,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'ذاكرة',
    titleAr: 'الذاكرة المادية',
    titleEn: 'Material Memory',
    storyAr: `في أنقاض الغرفة القديمة\nوجدت شيئاً صغيراً لم يحترق ولم يُكسر.\nشيئاً كان يوماً جزءاً عادياً من يومك.\nتمسك به بيدك.`,
    storyEn: `In the ruins of the old room\nyou found a small thing that didn\'t burn and didn\'t break.\nSomething that was once an ordinary part of your day.\nYou hold it in your hand.`,
    choices: [
      {
        textAr: 'تحمله معك. سيبقى معك دائماً.',
        textEn: 'You take it with you. It will stay with you always.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 15,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'في يدك الصغيرة حياة كاملة. لا يعرفها أحد غيرك. لكنها تكفي.',
        messageEn: 'In your small hand a whole life. No one knows it but you. But it is enough.',
      },
      {
        textAr: 'تضعه مجدداً في مكانه في الأنقاض',
        textEn: 'You put it back in its place in the ruins',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 8,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'تركته لأن هذا مكانه. لأن بعض الأشياء تنتمي لأرضها. وأنت تفهم هذا جيداً.',
        messageEn: 'You left it because this is its place. Because some things belong to their land. And you understand this well.',
      },
    ],
    realFactAr: 'عائدون لغزة: الأشياء الصغيرة الناجية من الدمار تصبح وثائق تاريخية حية.',
    realFactEn: 'Returnees to Gaza: Small objects surviving destruction become living historical documents.',
  },

  // ===== MONTH 34 =====
  {
    id: 'kayfa_halak',
    month: 34,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'نفس',
    titleAr: 'كيف حالك؟',
    titleEn: 'How Are You?',
    storyAr: `شخص تعرفه مرّ بك.\nابتسم وسأل ببساطة:\n"كيف حالك؟"\nوقفت.\nلا تعرف من أين تبدأ.`,
    storyEn: `Someone you know passed by you.\nSmiled and asked simply:\n"How are you?"\nYou stopped.\nYou don\'t know where to begin.`,
    choices: [
      {
        textAr: '"الحمد لله" — وتمشي',
        textEn: '"Praise God" — and you walk on',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: -3,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'ثلاث كلمات تحمل كل شيء ولا تقول شيئاً. لكنها الإجابة التي تحمي.',
        messageEn: 'Three words that hold everything and say nothing. But they are the answer that protects.',
      },
      {
        textAr: 'تجلس وتبدأ تتكلم — لأول مرة',
        textEn: 'You sit and begin to speak — for the first time',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 10,
        moraleEffect: 15,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'تكلمت لساعة. لم يقاطعك. بعض الجروح تحتاج شاهداً لتبدأ بالالتئام.',
        messageEn: 'You talked for an hour. He didn\'t interrupt you. Some wounds need a witness to begin healing.',
      },
      {
        textAr: 'تضحك بطريقة غريبة ولا تجيب',
        textEn: 'You laugh in a strange way and don\'t answer',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: -5,
        moraleEffect: 3,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'فهم. لم يسأل أكثر. أحياناً الفهم أعمق من الإجابة.',
        messageEn: 'He understood. He didn\'t ask more. Sometimes understanding is deeper than answering.',
      },
    ],
    realFactAr: 'منظمات الصحة النفسية: "اضطراب ما بعد الصدمة" يمس 97% من سكان غزة وفق الدراسات.',
    realFactEn: 'Mental health organizations: PTSD affects 97% of Gaza\'s population according to studies.',
  },

  // ===== MONTH 35 =====
  {
    id: 'al_tifl_yadhak_mujaddadan',
    month: 35,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'صمود',
    titleAr: 'الطفل يضحك مجدداً',
    titleEn: 'The Child Laughs Again',
    storyAr: `شيء صغير وغبي حدث.\nطفلك ضحك.\nليس ابتسامة. ضحك حقيقي.\nبصوت عالٍ.\nمن البطن.\nأنت نظرت إليه.\nوبكيت.`,
    storyEn: `Something small and silly happened.\nYour child laughed.\nNot a smile. A real laugh.\nOut loud.\nFrom the belly.\nYou looked at him.\nAnd you cried.`,
    choices: [
      {
        textAr: 'تبكي وتضحك معه في نفس الوقت',
        textEn: 'You cry and laugh with him at the same time',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 10,
        moraleEffect: 25,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'ضحكتم معاً وأنتم تبكون. لا يوجد في اللغة اسم لهذا الشعور. لكنه موجود.',
        messageEn: 'You laughed together while crying. There is no word in any language for this feeling. But it exists.',
      },
      {
        textAr: 'تتحول بعيداً لتخفي دموعك — لا تريده أن يرى',
        textEn: 'You turn away to hide your tears — you don\'t want him to see',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: 18,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'سمع شهيقك. التفت ونظر إليك بعيون تفهم أكثر مما ينبغي لطفل أن يفهم.',
        messageEn: 'He heard your inhale. He turned and looked at you with eyes that understand more than a child should.',
      },
    ],
    showOnlyIfChildren: true,
    realFactAr: 'علماء النفس: ضحكة الطفل في مناطق الحرب هي أكثر الأصوات إيلاماً وتعافياً في نفس الوقت.',
    realFactEn: 'Psychologists: A child\'s laugh in war zones is at once the most painful and the most healing sound.',
  },

  // ===== MONTH 36 =====
  {
    id: 'nihaya',
    month: 36,
    recurring: false,
    autoEvent: false,
    emotionalTheme: 'وطن',
    titleAr: 'نهاية',
    titleEn: 'The End',
    storyAr: `ستة وثلاثون شهراً.\nالحرب لم تنتهِ تماماً. أو ربما انتهت.\nلكن ما بداخلك لن ينتهي أبداً.\nأنت تقف الآن على عتبة ما يأتي بعد.\nما الذي ستحمله معك؟`,
    storyEn: `Thirty-six months.\nThe war did not end completely. Or perhaps it did.\nBut what is inside you will never end.\nYou stand now on the threshold of what comes after.\nWhat will you carry with you?`,
    choices: [
      {
        textAr: 'الاسم. أسماء كل من رحل.',
        textEn: 'The names. The names of all who left.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 10,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'الأسماء في صدرك. لن تسقط. هذه هي الطريقة الوحيدة التي لا تنتهي فيها الحرب بموت.',
        messageEn: 'The names in your chest. They won\'t fall. This is the only way the war doesn\'t end in death.',
      },
      {
        textAr: 'ضحكة طفلك. صوتها بالضبط.',
        textEn: 'Your child\'s laugh. Its exact sound.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 5,
        moraleEffect: 15,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'تحمل صوتاً. لا يثقل. لا يُكسر. لا ترمه أي قنبلة.',
        messageEn: 'You carry a sound. It has no weight. It cannot break. No bomb can throw it away.',
      },
      {
        textAr: 'شيئاً لا تسميه. لكنك تعرفه.',
        textEn: 'Something you can\'t name. But you know it.',
        oneTimeCost: 0,
        monthlyCost: 0,
        healthEffect: 0,
        moraleEffect: 12,
        deathRisk: 0,
        injuryRisk: 0,
        messageAr: 'بعض ما نحمله لا يحتاج كلمة. يكفي أن يكون موجوداً. يكفي أنك موجود.',
        messageEn: 'Some of what we carry needs no word. It is enough that it exists. It is enough that you exist.',
      },
    ],
    realFactAr: 'غزة 2026: أكثر من 55,000 شهيد. 1.8 مليون نازح. ومع ذلك — الناس لا يزالون يتذكرون أسماء بعضهم.',
    realFactEn: 'Gaza 2026: Over 55,000 martyred. 1.8 million displaced. And yet — people still remember each other\'s names.',
  },

];
